#!/usr/bin/env python3
"""Stage 1: Register 19 post-2020 G2 projects in 01_projects.csv."""
import csv
import os

DRIVE = os.path.expanduser("~/Library/CloudStorage/GoogleDrive-iain@thefifthsector.co.uk/My Drive")
CSV_PATH = os.path.join(DRIVE, "Website 2026/spillover-toolkit/01_projects.csv")

# Read existing to get header and check for duplicates
with open(CSV_PATH, "r", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    header = reader.fieldnames
    existing_ids = {row["project_id"] for row in reader}

print(f"Existing project IDs: {len(existing_ids)}")
print(f"Header fields: {len(header)}")

# 19 post-2020 projects (LCR Games dropped)
projects = [
    {
        "project_id": "P16-CICP",
        "canonical_name": "CICP Impact and Delivery Evaluation",
        "client": "UKRI / AHRC",
        "client_type": "public_body",
        "date_start": "2020",
        "date_end": "UNKNOWN",
        "lifecycle_status": "COMPLETED",
        "sector_activity": "evaluation_design",
        "geography": "national (UK)",
        "scope_decision": "Evaluation approach design for Creative Industries Clusters Programme and PEC",
        "fifth_sector_role": "ADVISOR;INTERPRETER",
        "intended_beneficiaries": "UKRI; AHRC; CICP clusters; PEC",
        "project_objectives": "Design evaluation framework for CICP including counterfactual methods and spillover capture",
        "source_coverage": "COMPLETE",
        "assessment_owner": "Iain",
        "assessment_status": "G2_assessed",
        "drive_folder_path": "Archive projects/Google project folders/2020/UKRI AHRC - Creative Industries Clusters Progr - (2020-2024)",
        "notes": "BOP Consulting prime with Frontier Economics; Iain contributed sector/workforce mapping and methodology design; marginal claim; evaluation approach document only not outcome report; 84 paras 1 table",
        "programme_status": "NOT_APPLICABLE",
        "contracting_role": "SUBCONTRACTOR",
        "prime_contractor": "BOP Consulting / Frontier Economics",
        "relationship_evidence": "Iain confirmed 2026-09-11: sector/workforce mapping and methodology design contribution via BOP",
        "review_status": "REVIEWED",
        "codebook_version": "1.3-candidate",
        "review_batch": "G2-BATCH-B",
    },
    {
        "project_id": "P17-LCRCSU",
        "canonical_name": "Leeds City Region Creative Scale Up Evidence Base",
        "client": "Leeds City Region / WYCA",
        "client_type": "combined_authority",
        "date_start": "2020",
        "date_end": "2020-07",
        "lifecycle_status": "COMPLETED",
        "sector_activity": "creative_industries_mapping",
        "geography": "Leeds City Region",
        "scope_decision": "Evidence base for Creative Scale Up programme bid",
        "fifth_sector_role": "DESIGNER;DELIVERER;LEAD_CONSULTANT",
        "intended_beneficiaries": "WYCA; creative businesses; LEP",
        "project_objectives": "Produce evidence base supporting Leeds City Region candidacy for Creative Scale Up extension",
        "source_coverage": "COMPLETE",
        "assessment_owner": "Iain",
        "assessment_status": "G2_assessed",
        "drive_folder_path": "Archive projects/2020 Projects/2020 Leeds City Region Creative Scale Up",
        "notes": "Iain Bennett lead consultant; 200 paras 1 table; bid evidence not outcome evaluation; BRES and ONS analysis; LQ cluster analysis; Channel 4 relocation context",
        "programme_status": "NOT_APPLICABLE",
        "contracting_role": "PRIME",
        "prime_contractor": "The Fifth Sector",
        "relationship_evidence": "Prepared by Iain Bennett The Fifth Sector Ltd (line 198); data credited to Fifth Sector (lines 20 35)",
        "review_status": "REVIEWED",
        "codebook_version": "1.3-candidate",
        "review_batch": "G2-BATCH-B",
    },
    {
        "project_id": "P18-GRIMSBY",
        "canonical_name": "Grimsby Cultural and Creative Industries Baseline",
        "client": "North East Lincolnshire Council / Magna Vitae",
        "client_type": "local_authority",
        "date_start": "2019",
        "date_end": "2020-03",
        "lifecycle_status": "COMPLETED",
        "sector_activity": "cultural_development_scoping",
        "geography": "Greater Grimsby / North East Lincolnshire",
        "scope_decision": "CDF scoping and programme development for Open for Culture programme",
        "fifth_sector_role": "ADVISOR;DATA_CONTRIBUTOR",
        "intended_beneficiaries": "NELC; Magna Vitae; Grimsby cultural sector; residents",
        "project_objectives": "Phase 1 research and recommendations for CDF Open for Culture programme",
        "source_coverage": "COMPLETE",
        "assessment_owner": "Iain",
        "assessment_status": "G2_assessed",
        "drive_folder_path": "Archive projects/2020 Projects/2020 Grimsby CCI",
        "notes": "Fifth Sector contributed mapping data; Magna Vitae authored report as delivery partner to NELC; 60 pages; participation baselines from national surveys; no economic output baselines; design propositions not outcomes",
        "programme_status": "NOT_APPLICABLE",
        "contracting_role": "SUBCONTRACTOR",
        "prime_contractor": "Magna Vitae",
        "relationship_evidence": "Iain confirmed 2026-09-11: Fifth Sector contributed mapping data to NE Lincs study",
        "review_status": "REVIEWED",
        "codebook_version": "1.3-candidate",
        "review_batch": "G2-BATCH-B",
    },
    {
        "project_id": "P19-LCRIMM",
        "canonical_name": "LCR Immersive Technology Sector Mapping",
        "client": "Growth Platform / LCR",
        "client_type": "combined_authority",
        "date_start": "2019",
        "date_end": "2020-05",
        "lifecycle_status": "COMPLETED",
        "sector_activity": "immersive_tech_sector_mapping",
        "geography": "Liverpool City Region",
        "scope_decision": "Mapping and strategy for immersive tech and content sector",
        "fifth_sector_role": "DESIGNER;DELIVERER;LEAD_CONSULTANT",
        "intended_beneficiaries": "Growth Platform; immersive tech SMEs; HEIs; investors",
        "project_objectives": "Map LCR immersive ecosystem and identify barriers and strategic opportunities",
        "source_coverage": "COMPLETE",
        "assessment_owner": "Iain",
        "assessment_status": "G2_assessed",
        "drive_folder_path": "Archive projects/2019 Projects/2019 LCR Growth Company Immersive tech",
        "notes": "Iain Bennett as BOP Consulting author (line 18); 57 pages; 169 organisations mapped; survey n=56; cross-sector case studies (Draw and Code Kinicho VEC/Bentley); work began 2019 delivered May 2020; listed as post-2020 replacement per Iain",
        "programme_status": "NOT_APPLICABLE",
        "contracting_role": "SUBCONTRACTOR",
        "prime_contractor": "BOP Consulting",
        "relationship_evidence": "Prepared by Iain Bennett and Marta Moretto BOP Consulting (line 18); Growth Platform commissioned from BOP (lines 121-122)",
        "review_status": "REVIEWED",
        "codebook_version": "1.3-candidate",
        "review_batch": "G2-BATCH-B",
    },
    {
        "project_id": "P20-SYMCA21",
        "canonical_name": "SYMCA Cultural and Creative Industries Research 2021",
        "client": "South Yorkshire Mayoral Combined Authority",
        "client_type": "combined_authority",
        "date_start": "2021-12",
        "date_end": "2022-06",
        "lifecycle_status": "COMPLETED",
        "sector_activity": "creative_industries_mapping",
        "geography": "South Yorkshire",
        "scope_decision": "Data research and mapping of creative sectors for SYMCA",
        "fifth_sector_role": "DESIGNER;DELIVERER;LEAD_CONSULTANT",
        "intended_beneficiaries": "SYMCA; creative businesses; sector organisations",
        "project_objectives": "Map creative industries scale profile and dynamics for policy and investment",
        "source_coverage": "COMPLETE",
        "assessment_owner": "Iain",
        "assessment_status": "G2_assessed",
        "drive_folder_path": "Archive projects/2021 Projects/2021 SYMCA CCI research",
        "notes": "Fifth Sector lead consultant with Curator Technologies and Morra; 324 paras; BRES LinkedIn IDBR Companies House FAME Beauhurst; 4000+ companies 31000 workforce vs 2895/13500 official; creative growth paradox finding",
        "programme_status": "NOT_APPLICABLE",
        "contracting_role": "PRIME",
        "prime_contractor": "The Fifth Sector",
        "relationship_evidence": "The Fifth Sector began work December 2021 (line 42); data credited throughout (lines 76 82 88 etc)",
        "review_status": "REVIEWED",
        "codebook_version": "1.3-candidate",
        "review_batch": "G2-BATCH-B",
    },
    {
        "project_id": "P21-MMUCCI",
        "canonical_name": "MMU Cultural and Creative Industries Positioning",
        "client": "Manchester Metropolitan University",
        "client_type": "university",
        "date_start": "2022-03",
        "date_end": "2022-08",
        "lifecycle_status": "COMPLETED",
        "sector_activity": "cci_positioning_audit",
        "geography": "Manchester",
        "scope_decision": "Strategic positioning and stakeholder engagement audit for MMU CCI offer",
        "fifth_sector_role": "DESIGNER;DELIVERER;LEAD_CONSULTANT",
        "intended_beneficiaries": "MMU; CCI sector; students; external stakeholders",
        "project_objectives": "Audit MMU CCI offer and recommend narrative and engagement improvements",
        "source_coverage": "COMPLETE",
        "assessment_owner": "Iain",
        "assessment_status": "G2_assessed",
        "drive_folder_path": "Archive projects/2021 Projects/2021 MMU CCI",
        "notes": "Fifth Sector lead consultant (www.thefifthsector.co.uk line 24); 521 paras; stakeholder interviews Mar-Aug 2022; desk research; benchmarking; no turnover/GVA baselines; REF 2021 results; network gap findings",
        "programme_status": "NOT_APPLICABLE",
        "contracting_role": "PRIME",
        "prime_contractor": "The Fifth Sector",
        "relationship_evidence": "Report carries www.thefifthsector.co.uk (line 24); Fifth Sector-delivered response (line 71)",
        "review_status": "REVIEWED",
        "codebook_version": "1.3-candidate",
        "review_batch": "G2-BATCH-B",
    },
    {
        "project_id": "P22-LCRFILM",
        "canonical_name": "LCR Film and TV Production Fund Interim Evaluation",
        "client": "Liverpool Film Office / Liverpool City Region",
        "client_type": "combined_authority",
        "date_start": "2020-09",
        "date_end": "2021-02",
        "lifecycle_status": "COMPLETED",
        "sector_activity": "film_fund_evaluation",
        "geography": "Liverpool City Region",
        "scope_decision": "Interim evaluation of LCR Film and TV Production Fund capital and revenue",
        "fifth_sector_role": "DESIGNER;DELIVERER;EVALUATOR;LEAD_CONSULTANT",
        "intended_beneficiaries": "Liverpool Film Office; LCR; film/TV productions; LCR crew",
        "project_objectives": "Evaluate fund delivery outputs and propose scenario options for recapitalisation",
        "source_coverage": "COMPLETE",
        "assessment_owner": "Iain",
        "assessment_status": "G2_assessed",
        "drive_folder_path": "Archive projects/2020 Projects/2020 Liverpool Film Fund evaluation",
        "notes": "Iain Bennett of The Fifth Sector for Liverpool Film Office (lines 225-231); 232 paras 5 tables; £6.76 leverage per £1; 455 indirect FTE; Development Fund seeded 7 pipeline projects; recoupment projections are estimates; richest documented output data in post-2020 cohort",
        "programme_status": "NOT_APPLICABLE",
        "contracting_role": "PRIME",
        "prime_contractor": "The Fifth Sector",
        "relationship_evidence": "Prepared by Iain Bennett of The Fifth Sector Limited for Liverpool Film Office (lines 225-231); tables sourced as Fifth Sector analysis (lines 71 96 103)",
        "review_status": "REVIEWED",
        "codebook_version": "1.3-candidate",
        "review_batch": "G2-BATCH-B",
    },
    {
        "project_id": "P23-DERBY",
        "canonical_name": "Derby and Derbyshire Screen Agency Feasibility",
        "client": "Derby City Council / Derbyshire County Council",
        "client_type": "local_authority",
        "date_start": "2022",
        "date_end": "2022-08",
        "lifecycle_status": "COMPLETED",
        "sector_activity": "feasibility_study",
        "geography": "Derby and Derbyshire",
        "scope_decision": "Feasibility study for joint Derby and Derbyshire Film Office",
        "fifth_sector_role": "DESIGNER;DELIVERER;LEAD_CONSULTANT",
        "intended_beneficiaries": "Derby City Council; Derbyshire County Council; screen sector",
        "project_objectives": "Assess feasibility of joint film office and recommend operating model",
        "source_coverage": "COMPLETE",
        "assessment_owner": "Iain",
        "assessment_status": "G2_assessed",
        "drive_folder_path": "Archive projects/2022 Projects/2022 Derby Screen Agency",
        "notes": "Fifth Sector lead consultant; 27 pages; survey n=17; Liverpool Film Office comparator; no local baseline data; design proposition for 2 FTE start-up; staged growth option",
        "programme_status": "NOT_APPLICABLE",
        "contracting_role": "PRIME",
        "prime_contractor": "The Fifth Sector",
        "relationship_evidence": "Document describes The Fifth Sector and its methods (line 11); commissioned by Derby City Council and Derbyshire County Council",
        "review_status": "REVIEWED",
        "codebook_version": "1.3-candidate",
        "review_batch": "G2-BATCH-B",
    },
    {
        "project_id": "P24-SYMCACGP",
        "canonical_name": "SYMCA Create Growth Programme Final Report",
        "client": "South Yorkshire Mayoral Combined Authority",
        "client_type": "combined_authority",
        "date_start": "2022",
        "date_end": "2022-12",
        "lifecycle_status": "COMPLETED",
        "sector_activity": "creative_industries_mapping",
        "geography": "South Yorkshire",
        "scope_decision": "Data research and mapping for SYMCA to inform Create Growth and Arts Culture Heritage strategy",
        "fifth_sector_role": "DESIGNER;DELIVERER;LEAD_CONSULTANT",
        "intended_beneficiaries": "SYMCA; creative businesses; sector organisations; education providers",
        "project_objectives": "Map CCI scale and dynamics and identify strategic opportunities for South Yorkshire",
        "source_coverage": "COMPLETE",
        "assessment_owner": "Iain",
        "assessment_status": "G2_assessed",
        "drive_folder_path": "Archive projects/2022 Projects/2022 SYMCA Create Growth",
        "notes": "Fifth Sector lead with Curator Technologies; 370 paras 4 tables; BRES LinkedIn IDBR Companies House FAME Beauhurst; 4025 companies 31000 workforce; GVA up to £2bn; creative growth paradox; 1013 courses; 5 apprenticeships; extends P20-SYMCA21 work",
        "programme_status": "NOT_APPLICABLE",
        "contracting_role": "PRIME",
        "prime_contractor": "The Fifth Sector",
        "relationship_evidence": "Cited as The Fifth Sector 2022 and The Fifth Sector/Curator Technologies 2022 throughout (lines 76 82 88 etc)",
        "review_status": "REVIEWED",
        "codebook_version": "1.3-candidate",
        "review_batch": "G2-BATCH-B",
    },
    {
        "project_id": "P25-LANCGP",
        "canonical_name": "Lancashire Create Growth Programme Bid",
        "client": "Lancashire LEP / Lancashire County Council",
        "client_type": "LEP",
        "date_start": "2022",
        "date_end": "2022-09",
        "lifecycle_status": "COMPLETED",
        "sector_activity": "bid_development",
        "geography": "Lancashire",
        "scope_decision": "DCMS Create Growth Programme full application for Lancashire",
        "fifth_sector_role": "DESIGNER;ADVISOR;DATA_CONTRIBUTOR",
        "intended_beneficiaries": "Lancashire LEP; creative businesses; Lancashire County Council",
        "project_objectives": "Develop DCMS Create Growth bid with evidence base and programme design",
        "source_coverage": "COMPLETE",
        "assessment_owner": "Iain",
        "assessment_status": "G2_assessed",
        "drive_folder_path": "Archive projects/2022 Projects/2022 Lancashire Create Growth",
        "notes": "Fifth Sector cited as data source (lines 197 1427 1430); applicant is Lancashire LEP/County Council; 42 pages; grant application not outcome report; 4500 businesses 36000 jobs; 4 hubs proposed; £1.275m budget; Pennine Originals spillover into aerospace/automotive",
        "programme_status": "UNKNOWN",
        "contracting_role": "SUBCONTRACTOR",
        "prime_contractor": "Lancashire LEP / Lancashire County Council",
        "relationship_evidence": "Fifth Sector analysis of Companies House via Beauhurst (lines 197 1427); Curator Technologies/Fifth Sector LinkedIn (lines 199 1430)",
        "review_status": "REVIEWED",
        "codebook_version": "1.3-candidate",
        "review_batch": "G2-BATCH-B",
    },
    {
        "project_id": "P26-WSBH",
        "canonical_name": "West Sussex Brighton and Hove Lewes CI Strategy",
        "client": "Greater Brighton Economic Board / Coastal West Sussex Partnership",
        "client_type": "partnership",
        "date_start": "2022-12",
        "date_end": "2023-04",
        "lifecycle_status": "COMPLETED",
        "sector_activity": "creative_industries_strategy",
        "geography": "West Sussex / Brighton and Hove / Lewes District",
        "scope_decision": "CI strategy with evidence base and mapping for sub-regional partnership",
        "fifth_sector_role": "DESIGNER;DELIVERER;LEAD_CONSULTANT",
        "intended_beneficiaries": "Greater Brighton Economic Board; Coastal West Sussex; creative businesses; universities",
        "project_objectives": "Map creative industries and develop strategy with recommendations",
        "source_coverage": "COMPLETE",
        "assessment_owner": "Iain",
        "assessment_status": "G2_assessed",
        "drive_folder_path": "Archive projects/2022 Projects/2022 West Sussex Brighton Hove Lewes",
        "notes": "Fifth Sector lead with Curator Technologies and Morra; 607 paras 6 tables; 10225 companies 54428 workforce; BRES 2021; Createch strengths; Digital Catapult Brighton; FuseBox24; Creative Assembly and Red River as anchor investors; 3-phase investment plan",
        "programme_status": "NOT_APPLICABLE",
        "contracting_role": "PRIME",
        "prime_contractor": "The Fifth Sector",
        "relationship_evidence": "The Fifth Sector began work December 2022 (line 75); Fifth Sector/Curator Technologies 2023 (lines 168 190 etc); Fifth Sector/Morra 2023 (line 387)",
        "review_status": "REVIEWED",
        "codebook_version": "1.3-candidate",
        "review_batch": "G2-BATCH-B",
    },
    {
        "project_id": "P27-WAKECDF",
        "canonical_name": "Wakefield Cultural Development Fund Evaluation",
        "client": "Wakefield Council",
        "client_type": "local_authority",
        "date_start": "2022",
        "date_end": "2025-09",
        "lifecycle_status": "COMPLETED",
        "sector_activity": "cultural_development_fund_evaluation",
        "geography": "Wakefield",
        "scope_decision": "Evaluation of CDF programme covering capital revenue skills and network development",
        "fifth_sector_role": "DESIGNER;DELIVERER;EVALUATOR;LEAD_CONSULTANT",
        "intended_beneficiaries": "Wakefield Council; Production Park; cultural organisations; residents",
        "project_objectives": "Evaluate CDF delivery outputs and assess value for money and legacy",
        "source_coverage": "COMPLETE",
        "assessment_owner": "Iain",
        "assessment_status": "G2_assessed",
        "drive_folder_path": "Archive projects/2025 Projects/2022 Wakefield CDF - Local Programme Evaluation",
        "notes": "Iain Bennett and Steve Hunt The Fifth Sector for Wakefield Council (line 11); 556 paras 14 tables; £4.38m CDF grant £22.03m total; CCI employment +32% 2020-2023; GVA +79%; Creative Wakefield +458% members; CoSTAR secured; 10 new-to-market products; INTERNAL INCONSISTENCY: 120 vs 160 FTE jobs; richest evaluation evidence in post-2020 cohort",
        "programme_status": "NOT_APPLICABLE",
        "contracting_role": "PRIME",
        "prime_contractor": "The Fifth Sector",
        "relationship_evidence": "Prepared by Iain Bennett and Steve Hunt The Fifth Sector Limited for Wakefield Council (line 11)",
        "review_status": "REVIEWED",
        "codebook_version": "1.3-candidate",
        "review_batch": "G2-BATCH-B",
    },
    {
        "project_id": "P28-CALDER",
        "canonical_name": "Calderdale CCI Research Report",
        "client": "Calderdale Council",
        "client_type": "local_authority",
        "date_start": "2023",
        "date_end": "2023-12",
        "lifecycle_status": "COMPLETED",
        "sector_activity": "creative_industries_mapping",
        "geography": "Calderdale",
        "scope_decision": "CCI research to inform investment planning 2024-2029",
        "fifth_sector_role": "DESIGNER;DELIVERER;LEAD_CONSULTANT",
        "intended_beneficiaries": "Calderdale Council; creative businesses; cultural organisations",
        "project_objectives": "Map CCI scale and dynamics and identify investment priorities",
        "source_coverage": "COMPLETE",
        "assessment_owner": "Iain",
        "assessment_status": "G2_assessed",
        "drive_folder_path": "Archive projects/2023 Projects/2023 Calderdale",
        "notes": "Produced by The Fifth Sector Limited (line 9); 639 paras 18 tables; ONS/IDBR BRES 2022 Companies House Beauhurst LinkedIn; 655 ONS firms 880 Beauhurst; 2360 BRES employment; 7375 LinkedIn workforce; music deep dive; Screen Yorkshire Connected Campus; Cultural Compact proposed",
        "programme_status": "NOT_APPLICABLE",
        "contracting_role": "PRIME",
        "prime_contractor": "The Fifth Sector",
        "relationship_evidence": "Produced by The Fifth Sector Limited on behalf of Calderdale Council (line 9)",
        "review_status": "REVIEWED",
        "codebook_version": "1.3-candidate",
        "review_batch": "G2-BATCH-B",
    },
    {
        "project_id": "P29-SOLENTCGP",
        "canonical_name": "Solent Create Growth Programme Bid Development",
        "client": "Solent LEP",
        "client_type": "LEP",
        "date_start": "2023",
        "date_end": "2023-09",
        "lifecycle_status": "COMPLETED",
        "sector_activity": "bid_development",
        "geography": "Solent",
        "scope_decision": "DCMS Create Growth Programme expansion full application for Solent",
        "fifth_sector_role": "DESIGNER;ADVISOR;DATA_CONTRIBUTOR",
        "intended_beneficiaries": "Solent LEP; creative businesses; universities",
        "project_objectives": "Develop CGP expansion bid with market awareness research and programme design",
        "source_coverage": "COMPLETE",
        "assessment_owner": "Iain",
        "assessment_status": "G2_assessed",
        "drive_folder_path": "Archive projects/2023 Projects/2023 Solent CGP",
        "notes": "Fifth Sector appointed as creative sector specialist consultancy for market awareness research (line 191); DRAFT application; 59 paras 6 tables; 4510 businesses 40000 jobs £1.5bn GVA; Createch cohort with maritime/aerospace/logistics spillovers; Solent Creative Investment Framework proposed",
        "programme_status": "UNKNOWN",
        "contracting_role": "SUBCONTRACTOR",
        "prime_contractor": "Solent LEP",
        "relationship_evidence": "Solent CGP appointed The Fifth Sector to conduct Market Awareness research (line 191)",
        "review_status": "REVIEWED",
        "codebook_version": "1.3-candidate",
        "review_batch": "G2-BATCH-B",
    },
    {
        "project_id": "P30-HEREFORD",
        "canonical_name": "Herefordshire Culture Strategy Review",
        "client": "Herefordshire Council",
        "client_type": "local_authority",
        "date_start": "2024",
        "date_end": "2024-06",
        "lifecycle_status": "COMPLETED",
        "sector_activity": "culture_strategy_review",
        "geography": "Herefordshire",
        "scope_decision": "Mid-point review of 10-year cultural strategy 2019-2029",
        "fifth_sector_role": "DESIGNER;DELIVERER;LEAD_CONSULTANT",
        "intended_beneficiaries": "Herefordshire Council; cultural sector; residents",
        "project_objectives": "Review progress of cultural strategy and recommend course corrections",
        "source_coverage": "COMPLETE",
        "assessment_owner": "Iain",
        "assessment_status": "G2_assessed",
        "drive_folder_path": "Archive projects/2024 Projects/2024 Herefordshire",
        "notes": "Iain confirmed 2026-09-11: Lead consultant; 225 paras; 590 official businesses 4000+ LinkedIn; 100 post-16 courses; 56% graduate leakage; rural creative economy models; fragmented ecosystem; cultural compact proposed; comparator analysis (Cornwall Cumbria Lincolnshire)",
        "programme_status": "NOT_APPLICABLE",
        "contracting_role": "PRIME",
        "prime_contractor": "The Fifth Sector",
        "relationship_evidence": "Iain confirmed lead consultant 2026-09-11",
        "review_status": "REVIEWED",
        "codebook_version": "1.3-candidate",
        "review_batch": "G2-BATCH-B",
    },
    {
        "project_id": "P31-PRODPARK",
        "canonical_name": "Production Park GVA Study",
        "client": "Production Park / Wakefield Council",
        "client_type": "partnership",
        "date_start": "2024",
        "date_end": "2024-07",
        "lifecycle_status": "COMPLETED",
        "sector_activity": "gva_data_fragment",
        "geography": "West Yorkshire / Wakefield",
        "scope_decision": "GVA data fragment for Production Park area",
        "fifth_sector_role": "DESIGNER;DELIVERER",
        "intended_beneficiaries": "Production Park; Wakefield Council",
        "project_objectives": "Provide employment and GVA data for Production Park area",
        "source_coverage": "COMPLETE",
        "assessment_owner": "Iain",
        "assessment_status": "G2_assessed",
        "drive_folder_path": "Archive projects/2024 Projects/2024 Production Park GVA",
        "notes": "Data fragment only; 11 paras 1 table; LinkedIn industry codes mapped to BRES SIC07; BRES 2022 columns empty; no narrative; no spillover evidence; incomplete extract; supplements P27-WAKECDF evaluation",
        "programme_status": "NOT_APPLICABLE",
        "contracting_role": "PRIME",
        "prime_contractor": "The Fifth Sector",
        "relationship_evidence": "Folder in Fifth Sector archive; supplements Wakefield CDF work",
        "review_status": "REVIEWED",
        "codebook_version": "1.3-candidate",
        "review_batch": "G2-BATCH-B",
    },
    {
        "project_id": "P32-SURREY",
        "canonical_name": "Surrey+ Creative Corridor Strategic Framework",
        "client": "Surrey County Council / Surrey+ partnership",
        "client_type": "partnership",
        "date_start": "2024",
        "date_end": "2025-08",
        "lifecycle_status": "COMPLETED",
        "sector_activity": "creative_corridor_strategy",
        "geography": "Surrey+ corridor",
        "scope_decision": "Regional creative economy strategy and investment framework",
        "fifth_sector_role": "DESIGNER;DELIVERER;LEAD_CONSULTANT",
        "intended_beneficiaries": "Surrey County Council; creative businesses; freelancers; universities",
        "project_objectives": "Develop creative corridor strategy with evidence base and investment case",
        "source_coverage": "COMPLETE",
        "assessment_owner": "Iain",
        "assessment_status": "G2_assessed",
        "drive_folder_path": "Archive projects/2024 Projects/2024 Surrey+ Corridor",
        "notes": "Iain confirmed 2026-09-11: Lead consultant; 212 paras; £7.2bn annual value; 17000 companies; 115000 workforce; 12% growth since 2019; 43% freelance; aerospace-to-screen spillover (Farnborough hangars to sound stages); CoSTAR/Games Innovation Zone; £3-4m investment ask with modelled returns",
        "programme_status": "NOT_APPLICABLE",
        "contracting_role": "PRIME",
        "prime_contractor": "The Fifth Sector",
        "relationship_evidence": "Iain confirmed lead consultant 2026-09-11",
        "review_status": "REVIEWED",
        "codebook_version": "1.3-candidate",
        "review_batch": "G2-BATCH-B",
    },
    {
        "project_id": "P33-LCRMUS",
        "canonical_name": "LCR Music Economy Mapping",
        "client": "Liverpool City Region",
        "client_type": "combined_authority",
        "date_start": "2025",
        "date_end": "2026-02",
        "lifecycle_status": "COMPLETED",
        "sector_activity": "music_economy_mapping",
        "geography": "Liverpool City Region",
        "scope_decision": "Economic mapping and analysis of LCR music economy",
        "fifth_sector_role": "DESIGNER;DELIVERER;LEAD_CONSULTANT",
        "intended_beneficiaries": "LCR; music businesses; musicians; Music Board",
        "project_objectives": "Map LCR music economy scale and dynamics and identify growth levers",
        "source_coverage": "COMPLETE",
        "assessment_owner": "Iain",
        "assessment_status": "G2_assessed",
        "drive_folder_path": "Archive projects/2025 Projects/2025 Liverpool Music",
        "notes": "The Fifth Sector Limited / Unscrambled.world with University of Liverpool IPM (lines 13-15); 650 paras 38 tables; four-tier workforce model; 14370 headcount 7215 FTE; £405.9m direct GVA £779.8m total; SNA of 272 businesses; 335 registered businesses 621 venues; Adlib cross-sector production services; £1bn by 2035 target; richest methodological innovation in post-2020 cohort",
        "programme_status": "NOT_APPLICABLE",
        "contracting_role": "PRIME",
        "prime_contractor": "The Fifth Sector",
        "relationship_evidence": "Produced by The Fifth Sector Limited / Unscrambled.world with University of Liverpool IPM (lines 13-15); tables cite Fifth Sector analysis throughout",
        "review_status": "REVIEWED",
        "codebook_version": "1.3-candidate",
        "review_batch": "G2-BATCH-B",
    },
    {
        "project_id": "P34-SOLENTHANTS",
        "canonical_name": "Solent and Hampshire CA CI Mapping",
        "client": "Solent and Hampshire Combined Authority",
        "client_type": "combined_authority",
        "date_start": "2025",
        "date_end": "2025-07",
        "lifecycle_status": "COMPLETED",
        "sector_activity": "creative_industries_mapping",
        "geography": "Solent and Hampshire",
        "scope_decision": "CI mapping and strategic economic analysis for SHCA",
        "fifth_sector_role": "DESIGNER;DELIVERER;LEAD_CONSULTANT",
        "intended_beneficiaries": "SHCA; creative businesses; freelancers; universities",
        "project_objectives": "Map CI scale and dynamics and identify strategic implications",
        "source_coverage": "COMPLETE",
        "assessment_owner": "Iain",
        "assessment_status": "G2_assessed",
        "drive_folder_path": "Archive projects/2025 Projects/2025 Solent and Hampshire CI",
        "notes": "Prepared by The Fifth Sector Limited (line 7) with Unscrambled; 354 paras 11 tables; £5.25bn GVA (reconciled); 39980 BRES employees 80511 LinkedIn workforce; 7530 IDBR businesses 11420 DataCity; HDBSCAN clustering; LQ analysis; 31% contraction in IT/software; freelancers as knowledge transfer agents",
        "programme_status": "NOT_APPLICABLE",
        "contracting_role": "PRIME",
        "prime_contractor": "The Fifth Sector",
        "relationship_evidence": "Prepared by The Fifth Sector Limited (line 7); Fifth Sector/Unscrambled cited throughout (lines 198 201 207 etc)",
        "review_status": "REVIEWED",
        "codebook_version": "1.3-candidate",
        "review_batch": "G2-BATCH-B",
    },
]

# Check for duplicates and collect new rows
new_rows = []
for p in projects:
    pid = p["project_id"]
    if pid in existing_ids:
        print(f"SKIP {pid}: already exists")
        continue
    # Fill in missing fields with defaults
    row = {h: p.get(h, "") for h in header}
    new_rows.append(row)
    print(f"ADD  {pid}: {p['canonical_name']}")

# Append
if new_rows:
    with open(CSV_PATH, "a", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=header)
        for row in new_rows:
            writer.writerow(row)
    print(f"\nAppended {len(new_rows)} projects to 01_projects.csv")
else:
    print("\nNo new projects to append")

print("Stage 1 complete.")
