#!/usr/bin/env python3
"""Stage 4b: Register G2 post-2020 claims batch 2 (P23-P34) in 04_claims.csv."""
import csv, os

CSV_PATH = os.path.expanduser("~/Library/CloudStorage/GoogleDrive-iain@thefifthsector.co.uk/My Drive/Website 2026/spillover-toolkit/04_claims.csv")

with open(CSV_PATH, "r", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    header = reader.fieldnames
    existing_ids = {row["claim_id"] for row in reader}

print(f"Existing claim IDs: {len(existing_ids)}")

claims = [
# P23-DERBY
("C-G2-042","P23-DERBY","Derby and Derbyshire film office feasibility established with 2 FTE staged start-up model and Liverpool Film Office comparator","OPTION","STAGE_LEARN","","The Fifth Sector","Derby City Council / Derbyshire County Council","INTENDED","UNKNOWN","BENEFICIAL","HYPOTHESIS","NOT_ASSESSED","NOT_APPLICABLE","INTENDED","WITHIN_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","DESIGNED_IN","FORECAST","BENEFICIAL","Derby/ Derbyshire screen sector","Design proposition not implemented","primary","UNKNOWN","COMPLETE","CONTEMPORARY","Survey n=17 not quantitative evidence base; Creative UK did not respond","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","DESIGN","M-G2-017","Feasibility design proposition; staged start-up with option to add grant/equity once demand proven; Liverpool comparator cost-neutral with 2 FTE and £100k budget","1.3-candidate","G2-BATCH-B"),

# P24-SYMCACGP
("C-G2-043","P24-SYMCACGP","South Yorkshire CCI estimated at up to £2bn GVA once freelance micro-enterprise indirect induced and visitor economy effects included","DIRECT","","","The Fifth Sector","SYMCA","INTENDED","2022","BENEFICIAL","REPORTED","DESCRIPTIVE","MONETARY","INTENDED","WITHIN_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","DESIGNED_IN","REALISED","BENEFICIAL","SYMCA","Sufficient from DCMS GVA and ONS productivity index","primary","UNKNOWN","COMPLETE","CONTEMPORARY","GVA uses generic ONS productivity index; BRES pre-pandemic","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","METHOD_OUTPUT","M-G2-018","Modelled estimate; £2bn incorporates freelance indirect induced and visitor economy; if as productive as national average would exceed £1bn; if South East level nearly £1.4bn","1.3-candidate","G2-BATCH-B"),
("C-G2-044","P24-SYMCACGP","Every 1 FTE directly employed in arts/culture supports total footprint of 2.46 FTE (0.62 indirect + 0.84 induced)","DIRECT","","","The Fifth Sector","SYMCA","INTENDED","2022","BENEFICIAL","REPORTED","DESCRIPTIVE","MONETARY","INTENDED","WITHIN_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","DESIGNED_IN","REALISED","BENEFICIAL","SYMCA","Sufficient from DCMS modelling","primary","UNKNOWN","COMPLETE","CONTEMPORARY","NONE_FOUND_IN_REVIEW","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","METHOD_OUTPUT","M-G2-018","Multiplier estimate from DCMS modelling; 2.46 total footprint per 1 FTE; contextual finding not intervention effect","1.3-candidate","G2-BATCH-B"),
("C-G2-045","P24-SYMCACGP","South Yorkshire has 1013 creative courses across region and wider TTWA but only 5 creative apprenticeships available","DIRECT","","","The Fifth Sector","SYMCA","INTENDED","2022","BENEFICIAL","REPORTED","DESCRIPTIVE","NON_MONETARY","INTENDED","WITHIN_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","DESIGNED_IN","REALISED","BENEFICIAL","SYMCA; creative students","Sufficient from course/qualification audit","primary","UNKNOWN","COMPLETE","CONTEMPORARY","Training gaps for Creative Content and alternative entry routes","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","METHOD_OUTPUT","M-G2-018","Skills mapping; 24 providers 331 courses in SYMCA; 548 wider TTWA; 134 online; 5 apprenticeships only; Sheffield 55% of delivery","1.3-candidate","G2-BATCH-B"),
("C-G2-046","P24-SYMCACGP","Time-limited policy windows (Levelling Up for Culture ACE Priority Places NP11) require urgent action to secure South Yorkshire benefit","OPTION","","","The Fifth Sector","SYMCA","INTENDED","UNKNOWN","BENEFICIAL","HYPOTHESIS","NOT_ASSESSED","NOT_APPLICABLE","INTENDED","WITHIN_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","DESIGNED_IN","FORECAST","BENEFICIAL","SYMCA; Barnsley/Doncaster/Rotherham","Policy windows time-limited","primary","UNKNOWN","COMPLETE","CONTEMPORARY","NONE_FOUND_IN_REVIEW","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","DESIGN","M-G2-018","Strategic option; Barnsley Doncaster Rotherham eligible for Levelling Up for Culture; ACE Priority Places; NP11 devolution agenda","1.3-candidate","G2-BATCH-B"),

# P25-LANCGP
("C-G2-047","P25-LANCGP","Lancashire creative economy comprises 4500 businesses and 36000 jobs (6% of workforce) with 980 new formations since April 2021","DIRECT","","","The Fifth Sector","Lancashire LEP","INTENDED","2022","BENEFICIAL","REPORTED","DESCRIPTIVE","MONETARY","INTENDED","WITHIN_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","OBSERVED","REALISED","BENEFICIAL","Lancashire creative sector","Sufficient from IDBR and Beauhurst","primary","UNKNOWN","COMPLETE","CONTEMPORARY","NONE_FOUND_IN_REVIEW","MEDIUM","DESIGNER;ADVISOR;DATA_CONTRIBUTOR","METHOD_OUTPUT","M-G2-019","Baseline mapping; IDBR April 2021; Fifth Sector/Beauhurst analysis; Blackpool 3400 creative workers; 400 vacancies","1.3-candidate","G2-BATCH-B"),
("C-G2-048","P25-LANCGP","Pennine Originals hub designed to develop technical textiles with explicit spillovers into aerospace and automotive sectors","PRODUCT","","","The Fifth Sector","Lancashire LEP","INTENDED","UNKNOWN","BENEFICIAL","HYPOTHESIS","NOT_ASSESSED","MONETARY","UNINTENDED","ACROSS_ORG","ACROSS_SECTOR","WITHIN_AREA","ACROSS_CHAIN","UNCOMPENSATED","DESIGNED_IN","FORECAST","BENEFICIAL","Textiles; aerospace; automotive","Design proposition in grant application","primary","UNKNOWN","COMPLETE","CONTEMPORARY","Grant application not outcome report","MEDIUM","DESIGNER;ADVISOR;DATA_CONTRIBUTOR","DESIGN","M-G2-019","Product spillover design proposition; Pennine Originals hub; technical textiles and homewares with spillovers into high-value sectors; from bid not delivered programme","1.3-candidate","G2-BATCH-B"),

# P26-WSBH
("C-G2-049","P26-WSBH","West Sussex Brighton Hove Lewes area has 10225 creative companies and 54428 workforce vs official 7470 businesses and 23690 employees","DIRECT","","","The Fifth Sector","Greater Brighton Economic Board / Coastal West Sussex","INTENDED","2023","BENEFICIAL","REPORTED","DESCRIPTIVE","MONETARY","INTENDED","WITHIN_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","DESIGNED_IN","REALISED","BENEFICIAL","Sub-regional partnership","Sufficient from BRES 2021 and LinkedIn","primary","UNKNOWN","COMPLETE","CONTEMPORARY","LinkedIn not directly comparable to BRES; 21000 freelance (38.9%)","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","METHOD_OUTPUT","M-G2-020","Baseline mapping; BRES 2021 22325 employment; LinkedIn 54428; Beauhurst 10255 active businesses 38.6% greater than official 7400","1.3-candidate","G2-BATCH-B"),
("C-G2-050","P26-WSBH","Createch strengths in immersive/VR/AR/XR and Virtual Production being adopted across film TV games animation and live experiences","PRODUCT","","","The Fifth Sector","Greater Brighton Economic Board","INTENDED","2023","BENEFICIAL","REPORTED","DESCRIPTIVE","MONETARY","UNINTENDED","ACROSS_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","UNCOMPENSATED","EMERGENT","REALISED","BENEFICIAL","Creative and digital businesses","Documented observation from mapping","primary","UNKNOWN","COMPLETE","CONTEMPORARY","Sector still to fully recover; start-up formation below trend","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","EFFECT","M-G2-020","Product spillover observation; Createch adoption across multiple sub-sectors; Digital Catapult Brighton and University of Brighton as institutional assets","1.3-candidate","G2-BATCH-B"),
("C-G2-051","P26-WSBH","Creative Assembly and Red River act as anchor investors supporting supply chain of smaller digital creative businesses and contractors","NETWORK","","","The Fifth Sector","Greater Brighton Economic Board","INTENDED","2023","BENEFICIAL","REPORTED","DESCRIPTIVE","NON_MONETARY","UNINTENDED","ACROSS_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","UNCOMPENSATED","EMERGENT","REALISED","BENEFICIAL","Digital creative supply chain","Sufficient from mapping and consultation","primary","UNKNOWN","COMPLETE","CONTEMPORARY","Brexit cost-of-living and property market headwinds","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","CONTEXT","M-G2-020","Network spillover observation; anchor firms support supply chain across games film TV and short-form content","1.3-candidate","G2-BATCH-B"),

# P27-WAKECDF
("C-G2-052","P27-WAKECDF","CDF programme delivered £22.03m total value from £4.38m grant with £6.06m private/partner capital leveraged","DIRECT","","","The Fifth Sector","Wakefield Council","INTENDED","2025","BENEFICIAL","REPORTED","DESCRIPTIVE","MONETARY","INTENDED","ACROSS_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","DESIGNED_IN","REALISED","BENEFICIAL","Wakefield cultural sector","Sufficient from financial records","primary","UNKNOWN","COMPLETE","CONTEMPORARY","Construction overruns required additional £2.1m Council funding","HIGH","DESIGNER;DELIVERER;EVALUATOR;LEAD_CONSULTANT","METHOD_OUTPUT","M-G2-021","Documented financial data; £4.38m CDF grant; £19.70m capital; £2.34m revenue; £13.64m public capital; £6.06m private leveraged","1.3-candidate","G2-BATCH-B"),
("C-G2-053","P27-WAKECDF","Wakefield CCI employment grew 32% (2210 to 2910) and estimated GVA grew 79% (£52.8m to £94.2m) 2020-2023","DIRECT","","","The Fifth Sector","Wakefield Council","INTENDED","2023","BENEFICIAL","REPORTED","DESCRIPTIVE","MONETARY","INTENDED","WITHIN_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","DESIGNED_IN","REALISED","BENEFICIAL","Wakefield creative sector","Sufficient from ONS BRES and DCMS estimates","primary","UNKNOWN","COMPLETE","CONTEMPORARY","GVA modelled not causal; report uses correlates with language; ONS business count fell slightly","MEDIUM","DESIGNER;DELIVERER;EVALUATOR;LEAD_CONSULTANT","METHOD_OUTPUT","M-G2-021","Modelled estimates not causal attribution; music/performing +194%; advertising +292%; design +133%; arts output £4.6m to £32.8m (+600%)","1.3-candidate","G2-BATCH-B"),
("C-G2-054","P27-WAKECDF","Creative Wakefield network grew 458% from 150 members (Apr 2020) to 837 (Oct 2024)","NETWORK","","","The Fifth Sector","Wakefield Council","INTENDED","2024","BENEFICIAL","REPORTED","DESCRIPTIVE","NON_MONETARY","UNINTENDED","ACROSS_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","UNCOMPENSATED","EMERGENT","REALISED","BENEFICIAL","Creative Wakefield members","Sufficient from membership data","primary","UNKNOWN","COMPLETE","CONTEMPORARY","NONE_FOUND_IN_REVIEW","HIGH","DESIGNER;DELIVERER;EVALUATOR;LEAD_CONSULTANT","EFFECT","M-G2-021","Documented network growth; 458% increase; direct network spillover indicator; website visits 58428 to 124527","1.3-candidate","G2-BATCH-B"),
("C-G2-055","P27-WAKECDF","XPLOR supported 10 enterprises to introduce new-to-market products and 20 to introduce new-to-firm products","PRODUCT","","","The Fifth Sector","Wakefield Council","INTENDED","2025","BENEFICIAL","REPORTED","DESCRIPTIVE","NON_MONETARY","UNINTENDED","ACROSS_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","UNCOMPENSATED","EMERGENT","REALISED","BENEFICIAL","XPLOR enterprises","Sufficient from monitoring data","primary","UNKNOWN","COMPLETE","CONTEMPORARY","NONE_FOUND_IN_REVIEW","HIGH","DESIGNER;DELIVERER;EVALUATOR;LEAD_CONSULTANT","EFFECT","M-G2-021","Documented product spillover; 10 new-to-market and 20 new-to-firm products; specific companies listed in Table 13","1.3-candidate","G2-BATCH-B"),
("C-G2-056","P27-WAKECDF","CDF catalysed strategic alliance between Wakefield Council and Production Park instrumental in securing CoSTAR Live Lab","NETWORK","","","The Fifth Sector","Wakefield Council","INTENDED","2025","BENEFICIAL","REPORTED","DESCRIPTIVE","NON_MONETARY","UNINTENDED","ACROSS_ORG","ACROSS_SECTOR","WITHIN_AREA","ACROSS_CHAIN","UNCOMPENSATED","EMERGENT","REALISED","BENEFICIAL","Production Park; Council","Interview testimony; causal claim","primary","UNKNOWN","COMPLETE","CONTEMPORARY","Attribution based on testimony not counterfactual experiment","MEDIUM","DESIGNER;DELIVERER;EVALUATOR;LEAD_CONSULTANT","EFFECT","M-G2-021","Network spillover; CDF provided financial bandwidth and confidence for Production Park to pursue CoSTAR; 4Wall and Tait established UK HQs; CoSTAR share of £75.6m","1.3-candidate","G2-BATCH-B"),
("C-G2-057","P27-WAKECDF","Creative Leadership programme produced 15 participants from 11 sub-sectors resulting in 12 new and ongoing cross-sector collaborations","KNOWLEDGE","","","The Fifth Sector","Wakefield Council","INTENDED","2025","BENEFICIAL","REPORTED","DESCRIPTIVE","NON_MONETARY","UNINTENDED","ACROSS_ORG","ACROSS_SECTOR","WITHIN_AREA","WITHIN_CHAIN","UNCOMPENSATED","EMERGENT","REALISED","BENEFICIAL","Creative leaders","Sufficient from programme monitoring","primary","UNKNOWN","COMPLETE","CONTEMPORARY","NONE_FOUND_IN_REVIEW","MEDIUM","DESIGNER;DELIVERER;EVALUATOR;LEAD_CONSULTANT","EFFECT","M-G2-021","Documented knowledge spillover; 15 participants 11 sub-sectors 12 cross-sector collaborations","1.3-candidate","G2-BATCH-B"),
("C-G2-058","P27-WAKECDF","INTERNAL INCONSISTENCY: Jobs created and safeguarded reported as 120 FTE in executive summary but 160 FTE in main body Table 14","CONTEXTUAL","","","The Fifth Sector","Wakefield Council","INTENDED","2025","BENEFICIAL","REPORTED","NOT_ASSESSED","NOT_APPLICABLE","INTENDED","WITHIN_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","DESIGNED_IN","REALISED","BENEFICIAL","Wakefield Council","Internal inconsistency in source document","primary","UNKNOWN","COMPLETE","CONTEMPORARY","Xcellerator 35 jobs (line 93) vs 30 jobs (Table 14)","HIGH","DESIGNER;DELIVERER;EVALUATOR;LEAD_CONSULTANT","CONTEXT","M-G2-021","Source inconsistency flagged; 120 FTE (exec summary Table 1 lines 96 563) vs 160 FTE (main body Table 14 lines 339 773); direct jobs 55; indirect 105 or 140 depending on source","1.3-candidate","G2-BATCH-B"),

# P28-CALDER
("C-G2-059","P28-CALDER","Calderdale CCI comprises 655 ONS firms (880 Beauhurst) with 2360 BRES employment but 7375 LinkedIn workforce indicating large freelance sector","DIRECT","","","The Fifth Sector","Calderdale Council","INTENDED","2023","BENEFICIAL","REPORTED","DESCRIPTIVE","MONETARY","INTENDED","WITHIN_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","DESIGNED_IN","REALISED","BENEFICIAL","Calderdale creative sector","Sufficient from ONS IDBR BRES Beauhurst LinkedIn","primary","UNKNOWN","COMPLETE","CONTEMPORARY","LinkedIn not comparable to BRES; 83% report employment status","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","METHOD_OUTPUT","M-G2-022","Baseline mapping; 1620 freelance (32% of LinkedIn sample); 3230 more workers than BRES; music deep dive 378 LinkedIn 273 MU members 63 licensed venues","1.3-candidate","G2-BATCH-B"),
("C-G2-060","P28-CALDER","New blended creative and digital skills in demand across health finance construction and other sectors","PRODUCT","","","The Fifth Sector","Calderdale Council","INTENDED","2023","BENEFICIAL","HYPOTHESIS","NOT_ASSESSED","MONETARY","UNINTENDED","ACROSS_ORG","ACROSS_SECTOR","WITHIN_AREA","ACROSS_CHAIN","UNCOMPENSATED","EMERGENT","FORECAST","BENEFICIAL","Health; finance; construction","Interpretation of skills-market data","primary","UNKNOWN","COMPLETE","CONTEMPORARY","Unclear if support would translate into economic benefit","LOW","DESIGNER;DELIVERER;LEAD_CONSULTANT","DESIGN","M-G2-022","Cross-sector skills demand hypothesis; Createch courses needed; Calderdale College planning games animation design film/TV esports motion-capture","1.3-candidate","G2-BATCH-B"),
("C-G2-061","P28-CALDER","Screen Yorkshire Connected Campus links TV/film professionals production companies broadcasters and students across Yorkshire HEIs and FE colleges","NETWORK","","","The Fifth Sector","Calderdale Council","INTENDED","2023","BENEFICIAL","REPORTED","DESCRIPTIVE","NON_MONETARY","UNINTENDED","ACROSS_ORG","ACROSS_SECTOR","WITHIN_AREA","WITHIN_CHAIN","UNCOMPENSATED","RETROSPECTIVE","REALISED","BENEFICIAL","Yorkshire screen sector","Sufficient from documented network","primary","UNKNOWN","COMPLETE","CONTEMPORARY","Unclear if Calderdale College plans to join Connected Campus","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","CONTEXT","M-G2-022","Network spillover observation; Screen Yorkshire as transferable model; BFI Northern Screen Alliance as regional network channel","1.3-candidate","G2-BATCH-B"),

# P29-SOLENTCGP
("C-G2-062","P29-SOLENTCGP","Solent has 4510 active CI businesses (10.7% of 42000 total) and 40000 CI jobs with £1.5bn GVA","DIRECT","","","The Fifth Sector","Solent LEP","INTENDED","2023","BENEFICIAL","REPORTED","DESCRIPTIVE","MONETARY","INTENDED","WITHIN_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","DESIGNED_IN","REALISED","BENEFICIAL","Solent creative sector","Sufficient from Beauhurst and Lightcast","primary","UNKNOWN","COMPLETE","CONTEMPORARY","Beauhurst 33% higher than IDBR; freelance not accurately measured","MEDIUM","DESIGNER;ADVISOR;DATA_CONTRIBUTOR","METHOD_OUTPUT","M-G2-023","Baseline mapping; Beauhurst Sept 2023; Lightcast 40000 jobs £1.5bn GVA; Oxford Economics 5000 new jobs by 2030 forecast","1.3-candidate","G2-BATCH-B"),
("C-G2-063","P29-SOLENTCGP","Createch cohort designed to develop IP for live events museums film/VFX virtual production and games with spillovers into maritime aerospace and logistics","PRODUCT","","","The Fifth Sector","Solent LEP","INTENDED","UNKNOWN","BENEFICIAL","HYPOTHESIS","NOT_ASSESSED","MONETARY","UNINTENDED","ACROSS_ORG","ACROSS_SECTOR","WITHIN_AREA","ACROSS_CHAIN","UNCOMPENSATED","DESIGNED_IN","FORECAST","BENEFICIAL","Maritime; aerospace; logistics","Design proposition in draft application","primary","UNKNOWN","COMPLETE","CONTEMPORARY","Draft application; no implementation outcomes","MEDIUM","DESIGNER;ADVISOR;DATA_CONTRIBUTOR","DESIGN","M-G2-023","Product spillover design proposition; digital twins for maritime/aerospace/logistics; projection mapping for live events; from draft bid not delivered programme","1.3-candidate","G2-BATCH-B"),

# P30-HEREFORD
("C-G2-064","P30-HEREFORD","Herefordshire has 590 official creative businesses but 4000+ LinkedIn professionals indicating large hidden freelance sector","DIRECT","","","The Fifth Sector","Herefordshire Council","INTENDED","2024","BENEFICIAL","REPORTED","DESCRIPTIVE","MONETARY","INTENDED","WITHIN_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","DESIGNED_IN","REALISED","BENEFICIAL","Herefordshire creative sector","Sufficient from ONS/DCMS and LinkedIn","primary","UNKNOWN","COMPLETE","CONTEMPORARY","Limited data collection obscures true sector size","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","METHOD_OUTPUT","M-G2-024","Baseline mapping; 590 official flat vs 2019; 4000+ LinkedIn c.3x larger; 56% graduate leakage; 58% no training in past year; 79% difficulty filling technical roles","1.3-candidate","G2-BATCH-B"),
("C-G2-065","P30-HEREFORD","Herefordshire can pioneer rural creative economy models with cross-cutting skills for agritech ecotourism and wellbeing","OPTION","","","The Fifth Sector","Herefordshire Council","INTENDED","UNKNOWN","BENEFICIAL","HYPOTHESIS","NOT_ASSESSED","MONETARY","UNINTENDED","ACROSS_ORG","ACROSS_SECTOR","WITHIN_AREA","ACROSS_CHAIN","UNCOMPENSATED","EMERGENT","FORECAST","BENEFICIAL","Agritech; ecotourism; wellbeing","Strategic hypothesis not realised","primary","UNKNOWN","COMPLETE","CONTEMPORARY","Fragmented ecosystem; flat business growth; ACE budgets down 35% real terms","LOW","DESIGNER;DELIVERER;LEAD_CONSULTANT","DESIGN","M-G2-024","Strategic option; rural creative economy model; cross-cutting skills for emerging markets; vision for 2029 beacon of rural cultural innovation","1.3-candidate","G2-BATCH-B"),

# P31-PRODPARK
("C-G2-066","P31-PRODPARK","Production Park area employment data fragment maps LinkedIn industry codes to BRES SIC07 for West Yorkshire/Wakefield","DIRECT","","","The Fifth Sector","Production Park / Wakefield Council","INTENDED","2024","BENEFICIAL","REPORTED","DESCRIPTIVE","NON_MONETARY","INTENDED","WITHIN_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","DESIGNED_IN","REALISED","BENEFICIAL","Production Park","Sufficient from data table","primary","UNKNOWN","COMPLETE","CONTEMPORARY","BRES 2022 columns empty; incomplete fragment","LOW","DESIGNER;DELIVERER","METHOD_OUTPUT","M-G2-025","Data fragment only; no narrative; no spillover evidence; supplements P27-WAKECDF; incomplete extract with empty columns","1.3-candidate","G2-BATCH-B"),

# P32-SURREY
("C-G2-067","P32-SURREY","Surrey+ creative corridor generates £7.2bn annually with 17000 companies and 115000 workforce growing 12% since 2019 vs UK average 2%","DIRECT","","","The Fifth Sector","Surrey County Council","INTENDED","2024","BENEFICIAL","REPORTED","DESCRIPTIVE","MONETARY","INTENDED","WITHIN_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","DESIGNED_IN","REALISED","BENEFICIAL","Surrey+ creative sector","Sufficient from mapping evidence","primary","UNKNOWN","COMPLETE","CONTEMPORARY","Underlying data sources not shown in text","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","METHOD_OUTPUT","M-G2-026","Baseline mapping; 43% freelance; 90% micro-businesses <5 employees; 12% growth vs 2% UK average","1.3-candidate","G2-BATCH-B"),
("C-G2-068","P32-SURREY","Farnborough aircraft hangars converted to sound stages translating aerospace technology into screen production innovation","PRODUCT","","","The Fifth Sector","Surrey County Council","INTENDED","2024","BENEFICIAL","REPORTED","DESCRIPTIVE","NON_MONETARY","UNINTENDED","ACROSS_ORG","ACROSS_SECTOR","WITHIN_AREA","ACROSS_CHAIN","UNCOMPENSATED","EMERGENT","REALISED","BENEFICIAL","Screen production; aerospace","Documented example","primary","UNKNOWN","COMPLETE","CONTEMPORARY","NONE_FOUND_IN_REVIEW","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","EFFECT","M-G2-026","Product spillover observation; aerospace-to-screen technology transfer; Sony Professional at Pinewood developing camera systems for Warner Bros/Apple F1 movie","1.3-candidate","G2-BATCH-B"),
("C-G2-069","P32-SURREY","£3-4m strategic investment over 3 years could catalyse 450-600 new jobs £15-20m economic value and over £30m private investment (modelled forecast)","OPTION","STAGE_LEARN","","The Fifth Sector","Surrey County Council","INTENDED","UNKNOWN","BENEFICIAL","HYPOTHESIS","NOT_ASSESSED","MONETARY","INTENDED","ACROSS_ORG","ACROSS_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","DESIGNED_IN","FORECAST","BENEFICIAL","Surrey+ creative sector","Modelled forecast not observed outcome","primary","UNKNOWN","COMPLETE","CONTEMPORARY","Other regions already building stronger strategies; no South East earmarked funding","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","DESIGN","M-G2-026","Investment forecast; £4 return per £1 invested; comparator benchmarks 2.8x investment returns 37% faster innovation commercialisation 42% better talent retention; modelled design proposition","1.3-candidate","G2-BATCH-B"),

# P33-LCRMUS
("C-G2-070","P33-LCRMUS","LCR music economy generates £405.9m direct GVA (Integrated Case) and £779.8m total economic impact (Type II multiplier 1.92)","DIRECT","","","The Fifth Sector","Liverpool City Region","INTENDED","2025","BENEFICIAL","REPORTED","DESCRIPTIVE","MONETARY","INTENDED","WITHIN_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","DESIGNED_IN","REALISED","BENEFICIAL","LCR music sector","Sufficient from four-tier workforce model","primary","UNKNOWN","COMPLETE","CONTEMPORARY","Tier 4 data quality low (50% confidence); LinkedIn coverage ~45%","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","METHOD_OUTPUT","M-G2-027","Modelled estimate; four-tier workforce model; 14370 headcount 7215 FTE; Base Case £324.7m direct; GVA per FTE by subsector ranges £25174 (Artists) to £145798 (Publishing)","1.3-candidate","G2-BATCH-B"),
("C-G2-071","P33-LCRMUS","Adlib Audio serves major touring productions festivals and corporate events across UK and internationally — music-sector technical services sold into non-music markets","PRODUCT","","","The Fifth Sector","Liverpool City Region","INTENDED","2025","BENEFICIAL","REPORTED","DESCRIPTIVE","MONETARY","UNINTENDED","ACROSS_ORG","ACROSS_SECTOR","WITHIN_AREA","ACROSS_CHAIN","UNCOMPENSATED","EMERGENT","REALISED","BENEFICIAL","Production services; non-music events","Documented business fact","primary","UNKNOWN","COMPLETE","CONTEMPORARY","Departure of any Tier 1 employer would materially damage ecosystem","HIGH","DESIGNER;DELIVERER;LEAD_CONSULTANT","EFFECT","M-G2-027","Product spillover observation; Adlib cross-sector production services; anchor firm in live/technical cluster as economic moat; proprietary data on casual crew across venues","1.3-candidate","G2-BATCH-B"),
("C-G2-072","P33-LCRMUS","SNA of 272 LCR music businesses shows 12% of connections within closed triangles but only 0.6% of possible connections exist with average degree 1.67","NETWORK","","","The Fifth Sector","Liverpool City Region","INTENDED","2025","BENEFICIAL","REPORTED","CO_AUTHORED_ANALYSIS","NON_MONETARY","UNINTENDED","ACROSS_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","UNCOMPENSATED","RETROSPECTIVE","REALISED","BENEFICIAL","LCR music businesses","Sufficient from SNA results","primary","UNKNOWN","COMPLETE","CONTEMPORARY","Network topology is diffuse; limits claims of dense network spillovers","HIGH","DESIGNER;DELIVERER;LEAD_CONSULTANT","METHOD_OUTPUT","M-G2-027","SNA of 272 businesses; workers moving with clear intention between small number of organisations; high interdependence suggests revenue retained in regional economy; but low connectivity limits spillover claims","1.3-candidate","G2-BATCH-B"),
("C-G2-073","P33-LCRMUS","£1bn by 2035 target requires 2.5% CAGR from £780m baseline with growth levers: IP capture (£100m) production export (£75m) formalisation (£60m) venues (£50m) music-tech (£43m)","OPTION","STAGE_LEARN","","The Fifth Sector","Liverpool City Region","INTENDED","UNKNOWN","BENEFICIAL","HYPOTHESIS","NOT_ASSESSED","MONETARY","INTENDED","WITHIN_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","DESIGNED_IN","FORECAST","BENEFICIAL","LCR music sector","Modelled targets not realised outcomes","primary","UNKNOWN","COMPLETE","CONTEMPORARY","Management/ Business Services LQ 0.37; career development and IP capture leak to London","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","DESIGN","M-G2-027","Growth scenarios: Organic 2.5% CAGR Accelerated 3.9% Ambitious 5.6% Transformational 6.7%; 4 growth levers with modelled GVA targets; IP capture option £40-85m shift","1.3-candidate","G2-BATCH-B"),
("C-G2-074","P33-LCRMUS","Moving 20% of artists from performance-fee-only to performance-plus-IP-ownership could shift £40-85m in captured GVA","OPTION","","","The Fifth Sector","Liverpool City Region","INTENDED","UNKNOWN","BENEFICIAL","HYPOTHESIS","NOT_ASSESSED","MONETARY","UNINTENDED","ACROSS_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","UNCOMPENSATED","DESIGNED_IN","FORECAST","BENEFICIAL","LCR artists and musicians","Modelled design proposition","primary","UNKNOWN","COMPLETE","CONTEMPORARY","IP capture leaks to London; streaming revenue decline","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","DESIGN","M-G2-027","IP capture option; modelled design proposition; MusicFutures positioned to build local capture infrastructure; formalisation of 500 freelancers could add £40-50m direct GVA","1.3-candidate","G2-BATCH-B"),

# P34-SOLENTHANTS
("C-G2-075","P34-SOLENTHANTS","Solent and Hampshire CA creative industries estimated at £5.25bn GVA (reconciled) with 39980 BRES employees and 80511 LinkedIn workforce","DIRECT","","","The Fifth Sector","Solent and Hampshire CA","INTENDED","2025","BENEFICIAL","REPORTED","DESCRIPTIVE","MONETARY","INTENDED","WITHIN_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","DESIGNED_IN","REALISED","BENEFICIAL","SHCA creative sector","Sufficient from ONS BRES DataCity LinkedIn DCMS","primary","UNKNOWN","COMPLETE","CONTEMPORARY","DCMS top-down £6.9bn almost certainly overestimate; 31% IT contraction","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","METHOD_OUTPUT","M-G2-028","Reconciled GVA estimate; ONS regional output £3.4bn; DCMS scaled £6.9bn overestimate; 7530 IDBR 11420 DataCity; 12700 freelance (17%) 23000+ contractors (31%)","1.3-candidate","G2-BATCH-B"),
("C-G2-076","P34-SOLENTHANTS","Freelancers play critical role in innovation and knowledge transfer between creative firms and other sectors and between universities and cultural organisations","KNOWLEDGE","","","The Fifth Sector","Solent and Hampshire CA","INTENDED","2025","BENEFICIAL","REPORTED","DESCRIPTIVE","NON_MONETARY","UNINTENDED","ACROSS_ORG","ACROSS_SECTOR","WITHIN_AREA","ACROSS_CHAIN","UNCOMPENSATED","EMERGENT","REALISED","BENEFICIAL","Freelancers; creative firms; universities","Interpretation from LinkedIn analysis","primary","UNKNOWN","COMPLETE","CONTEMPORARY","LinkedIn over-represents advertising/design 6-8x BRES","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","CONTEXT","M-G2-028","Knowledge spillover interpretation; 23000+ independent professionals (31%); Creative Trident concept; co-location of creative and professional services driving innovation","1.3-candidate","G2-BATCH-B"),
("C-G2-077","P34-SOLENTHANTS","SHCA creative economy is network of interconnected specialised hubs with B2B ecosystem co-locating creative with professional services","NETWORK","","","The Fifth Sector","Solent and Hampshire CA","INTENDED","2025","BENEFICIAL","REPORTED","DESCRIPTIVE","NON_MONETARY","UNINTENDED","ACROSS_ORG","ACROSS_SECTOR","WITHIN_AREA","WITHIN_CHAIN","UNCOMPENSATED","RETROSPECTIVE","REALISED","BENEFICIAL","SHCA creative sector","Interpretation from HDBSCAN and LQ mapping","primary","UNKNOWN","COMPLETE","CONTEMPORARY","HDBSCAN caveat: accountants in all but 3 postcode areas","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","CONTEXT","M-G2-028","Network spillover interpretation; advertising/marketing co-located with professional services; Services supply chain 31246 and Tech supply chain 21387; HDBSCAN spatial clustering","1.3-candidate","G2-BATCH-B"),
]

new_rows = []
for c in claims:
    cid = c[0]
    if cid in existing_ids:
        print(f"SKIP {cid}")
        continue
    row = {h: c[i] if i < len(c) else "" for i, h in enumerate(header)}
    new_rows.append(row)
    print(f"ADD  {cid}: {c[1]}")

if new_rows:
    with open(CSV_PATH, "a", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=header)
        for row in new_rows:
            writer.writerow(row)
    print(f"\nAppended {len(new_rows)} claims (batch 2)")
print("Stage 4b complete.")
