#!/usr/bin/env python3
"""Stage 4a: Register G2 post-2020 claims batch 1 (P16-P22) in 04_claims.csv."""
import csv, os

CSV_PATH = os.path.expanduser("~/Library/CloudStorage/GoogleDrive-iain@thefifthsector.co.uk/My Drive/Website 2026/spillover-toolkit/04_claims.csv")

with open(CSV_PATH, "r", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    header = reader.fieldnames
    existing_ids = {row["claim_id"] for row in reader}

print(f"Existing claim IDs: {len(existing_ids)}")
print(f"Header fields: {len(header)}")

# Claims batch 1: P16-CICP through P22-LCRFILM
# Using compact tuple format: (claim_id, project_id, proposition, effect_family, mechanism, option_subtype, originator, recipient, intended_beneficiary_status, event_period, claim_direction, outcome_status, attribution_strength, value_status, boundary_recipient, boundary_org, boundary_sector, boundary_geography, boundary_chain, compensation, intent, timing, direction, beneficiaries, evidence_sufficiency, source_quality, independence, coverage, time_lag, contrary_evidence, reviewer_confidence, fifth_sector_role, claim_type, method_ids, notes, codebook_version, review_batch)
# Fields not in tuple default to empty string

claims = [
# P16-CICP
("C-G2-024","P16-CICP","CICP evaluation approach designed with mixed-methods contribution analysis CBA DiD and LinkedIn/Meetup network mapping","DIRECT","","","BOP Consulting / Iain Bennett","UKRI / AHRC","INTENDED","2020","BENEFICIAL","REPORTED","DESCRIPTIVE","NOT_APPLICABLE","INTENDED","WITHIN_ORG","ACROSS_SECTOR","NATIONAL","WITHIN_CHAIN","COMPENSATED","DESIGNED_IN","REALISED","BENEFICIAL","UKRI; AHRC; CICP clusters","Sufficient from approach document","primary","UNKNOWN","COMPLETE","CONTEMPORARY","Diversity of interventions and places makes attribution hard","MEDIUM","ADVISOR;INTERPRETER","METHOD_OUTPUT","M-G2-010","Evaluation approach design not outcome report; Iain contributed mapping and methodology via BOP; marginal claim","1.3-candidate","G2-BATCH-B"),

# P17-LCRCSU
("C-G2-025","P17-LCRCSU","Leeds City Region creative industries employment grew 32% (14420 jobs) 2015-2018 to 58840","DIRECT","","","The Fifth Sector","WYCA","INTENDED","2018","BENEFICIAL","REPORTED","DESCRIPTIVE","MONETARY","INTENDED","WITHIN_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","OBSERVED","REALISED","BENEFICIAL","WYCA; creative businesses","Sufficient from BRES data","primary","UNKNOWN","COMPLETE","CONTEMPORARY","Overall growth lower than national average","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","METHOD_OUTPUT","M-G2-011","Baseline growth measurement not intervention effect; BRES time series; Film/TV +91% IT +81% Music +75%","1.3-candidate","G2-BATCH-B"),
("C-G2-026","P17-LCRCSU","Increasing importance of creative content and digital technology in other industries including smart cities energy health fintech and manufacturing","PRODUCT","","","The Fifth Sector","WYCA","INTENDED","UNKNOWN","BENEFICIAL","HYPOTHESIS","NOT_ASSESSED","MONETARY","UNINTENDED","ACROSS_ORG","ACROSS_SECTOR","WITHIN_AREA","ACROSS_CHAIN","UNCOMPENSATED","EMERGENT","FORECAST","BENEFICIAL","Multiple sectors","Interpretation from strategy documents and industry surveys","primary","UNKNOWN","COMPLETE","CONTEMPORARY","NONE_FOUND_IN_REVIEW","LOW","DESIGNER;LEAD_CONSULTANT","DESIGN","M-G2-011","Cross-sector spillover forecast; bid evidence not measured outcome; immersive tech expected to move beyond creative industries","1.3-candidate","G2-BATCH-B"),

# P18-GRIMSBY
("C-G2-027","P18-GRIMSBY","Grimsby has among lowest arts participation in England (27.3% vs 34.6% national) establishing baseline need for cultural intervention","DIRECT","","","The Fifth Sector","NELC / Magna Vitae","INTENDED","2017","BENEFICIAL","REPORTED","DESCRIPTIVE","NON_MONETARY","INTENDED","WITHIN_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","DESIGNED_IN","REALISED","BENEFICIAL","Grimsby residents","Sufficient from Active Lives Survey","primary","UNKNOWN","COMPLETE","CONTEMPORARY","Local sector is insular; funding dependent on NELC/ACE","MEDIUM","ADVISOR;DATA_CONTRIBUTOR","CONTEXT","M-G2-012","Participation baseline from national surveys; Fifth Sector contributed mapping data; Magna Vitae authored report; contextual finding not intervention effect","1.3-candidate","G2-BATCH-B"),

# P19-LCRIMM
("C-G2-028","P19-LCRIMM","LCR immersive ecosystem comprises 169 organisations (126 companies 114 LCR-based) with estimated 600+ workforce","DIRECT","","","BOP Consulting / Iain Bennett","Growth Platform","INTENDED","2020","BENEFICIAL","REPORTED","DESCRIPTIVE","MONETARY","INTENDED","WITHIN_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","DESIGNED_IN","REALISED","BENEFICIAL","Immersive tech SMEs","Sufficient from AI web search and LinkedIn","primary","UNKNOWN","COMPLETE","CONTEMPORARY","SIC/SOC codes cannot capture immersive; survey self-selecting","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","METHOD_OUTPUT","M-G2-013","Baseline mapping; 169 organisations; LinkedIn workforce 190 highly skilled; estimated 600+ total; Iain Bennett as BOP author","1.3-candidate","G2-BATCH-B"),
("C-G2-029","P19-LCRIMM","Immersive technologies applied across 25+ non-creative sectors including aerospace automotive defence education health manufacturing retail","PRODUCT","","","BOP Consulting / Iain Bennett","Growth Platform","INTENDED","2020","BENEFICIAL","REPORTED","DESCRIPTIVE","MONETARY","UNINTENDED","ACROSS_ORG","ACROSS_SECTOR","WITHIN_AREA","ACROSS_CHAIN","UNCOMPENSATED","EMERGENT","REALISED","BENEFICIAL","Multiple sectors","Sufficient from case studies","primary","UNKNOWN","COMPLETE","CONTEMPORARY","Demand beyond gaming uncertain; VR distribution segmented","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","EFFECT","M-G2-013","Documented cross-sector case studies: Draw and Code (AR museums/SwapBots) Kinicho (volumetric audio for Audible/Pinewood/CERN) VEC/Bentley (immersive design) Shaun the Sheep/Aardman (AI sensor tech Shanghai)","1.3-candidate","G2-BATCH-B"),
("C-G2-030","P19-LCRIMM","LCR immersive sector has active Meetup ecosystem and supply-chain relationships connecting creative digital manufacturing health and logistics","NETWORK","","","BOP Consulting / Iain Bennett","Growth Platform","INTENDED","2020","BENEFICIAL","REPORTED","DESCRIPTIVE","NON_MONETARY","UNINTENDED","ACROSS_ORG","ACROSS_SECTOR","WITHIN_AREA","ACROSS_CHAIN","UNCOMPENSATED","EMERGENT","REALISED","BENEFICIAL","Immersive tech companies; end-users","Sufficient from mapping and survey","primary","UNKNOWN","COMPLETE","CONTEMPORARY","LCR smaller than Manchester less mature than Bristol","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","METHOD_OUTPUT","M-G2-013","Network spillover observation; large end-users include Alstom Cammell Laird JLR Royal HaskoningDHV; supply chain includes Adlib Lime Pictures","1.3-candidate","G2-BATCH-B"),
("C-G2-031","P19-LCRIMM","Multiple gated investment options proposed: Institute of Creative Technology demonstrator facilities large-scale XR venue and North West regional cluster","OPTION","STAGE_LEARN","","BOP Consulting / Iain Bennett","Growth Platform","INTENDED","UNKNOWN","BENEFICIAL","HYPOTHESIS","NOT_ASSESSED","NOT_APPLICABLE","INTENDED","ACROSS_ORG","ACROSS_SECTOR","WITHIN_AREA","WITHIN_CHAIN","UNCOMPENSATED","DESIGNED_IN","FORECAST","BENEFICIAL","Growth Platform; immersive SMEs","Proposed not implemented","primary","UNKNOWN","COMPLETE","CONTEMPORARY","NONE_FOUND_IN_REVIEW","MEDIUM","DESIGNER;LEAD_CONSULTANT","DESIGN","M-G2-013","Design propositions for multiple staged investment options; option held by Growth Platform not Fifth Sector","1.3-candidate","G2-BATCH-B"),

# P20-SYMCA21
("C-G2-032","P20-SYMCA21","South Yorkshire creative industries comprise 4000+ companies and 31000 workforce vs official 2895 businesses and 13500 employees","DIRECT","","","The Fifth Sector","SYMCA","INTENDED","2022","BENEFICIAL","REPORTED","DESCRIPTIVE","MONETARY","INTENDED","WITHIN_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","DESIGNED_IN","REALISED","BENEFICIAL","SYMCA; creative sector","Sufficient from BRES LinkedIn IDBR Companies House","primary","UNKNOWN","COMPLETE","CONTEMPORARY","BRES excludes freelancers and micro-enterprises below VAT threshold","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","METHOD_OUTPUT","M-G2-014","Baseline mapping; LinkedIn captures freelancers missed by BRES; 60% freelance estimated; Companies House cleansed 4025 businesses","1.3-candidate","G2-BATCH-B"),
("C-G2-033","P20-SYMCA21","Creative growth paradox: large number of businesses and workforce growth coexists with very low R&D grants equity investment spinouts and scale-ups","CONTEXTUAL","","","The Fifth Sector","SYMCA","INTENDED","2022","BENEFICIAL","REPORTED","DESCRIPTIVE","NOT_APPLICABLE","UNINTENDED","WITHIN_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","UNCOMPENSATED","RETROSPECTIVE","REALISED","BENEFICIAL","SYMCA; creative businesses","Sufficient from Beauhurst and Companies House analysis","primary","UNKNOWN","COMPLETE","CONTEMPORARY","NONE_FOUND_IN_REVIEW","HIGH","DESIGNER;DELIVERER;LEAD_CONSULTANT","CONTEXT","M-G2-014","Key finding: 4.8% file full accounts; <2% accessed R&D grants; 36 equity investments; 8 spinouts; 6 scale-ups; important for methodology development","1.3-candidate","G2-BATCH-B"),
("C-G2-034","P20-SYMCA21","South Yorkshire free-riding on Screen Yorkshire for inward investment talent and crew services is unsustainable","NETWORK","","","The Fifth Sector","SYMCA","INTENDED","2022","BENEFICIAL","REPORTED","DESCRIPTIVE","NON_MONETARY","UNINTENDED","ACROSS_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","UNCOMPENSATED","RETROSPECTIVE","REALISED","BENEFICIAL","SYMCA; Screen Yorkshire","Sufficient from consultation and analysis","primary","UNKNOWN","COMPLETE","CONTEMPORARY","NONE_FOUND_IN_REVIEW","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","CONTEXT","M-G2-014","Network dependency finding; recommendation to agree formal support package with Screen Yorkshire","1.3-candidate","G2-BATCH-B"),

# P21-MMUCCI
("C-G2-035","P21-MMUCCI","MMU research excellence is largely invisible to external stakeholders despite REF 2021 ranking second in UK for art and design research power","CONTEXTUAL","","","The Fifth Sector","MMU","INTENDED","2022","BENEFICIAL","REPORTED","DESCRIPTIVE","NOT_APPLICABLE","INTENDED","WITHIN_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","DESIGNED_IN","REALISED","BENEFICIAL","MMU; CCI sector","Sufficient from stakeholder interviews and desk research","primary","UNKNOWN","COMPLETE","CONTEMPORARY","85% of arts/humanities outputs receive no citations","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","CONTEXT","M-G2-015","Contextual finding; internal research excellence contrasts with external stakeholder awareness; 70% world-leading English research impact","1.3-candidate","G2-BATCH-B"),
("C-G2-036","P21-MMUCCI","MMU weakly connected to Manchester business networks (IOD Manchester Digital Pro Manchester) and BBC/Creative UK relationship is transactional","NETWORK","","","The Fifth Sector","MMU","INTENDED","2022","BENEFICIAL","REPORTED","DESCRIPTIVE","NON_MONETARY","INTENDED","ACROSS_ORG","ACROSS_SECTOR","WITHIN_AREA","WITHIN_CHAIN","UNCOMPENSATED","RETROSPECTIVE","REALISED","BENEFICIAL","MMU","Sufficient from stakeholder interviews","primary","UNKNOWN","COMPLETE","CONTEMPORARY","VC dominates external dialogue; alumni engagement weak","MEDIUM","DESIGNER;DELIVERER;LEAD_CONSULTANT","CONTEXT","M-G2-015","Network gap finding; recommendation to overhaul account management and strengthen links to business networks","1.3-candidate","G2-BATCH-B"),

# P22-LCRFILM
("C-G2-037","P22-LCRFILM","LCR Film Fund generated £12.08m LCR spend from £1.788m invested — £6.76 leverage per £1 (target 3:1 film 5:1 TV)","DIRECT","","","The Fifth Sector","Liverpool Film Office","INTENDED","2021","BENEFICIAL","REPORTED","DESCRIPTIVE","MONETARY","INTENDED","ACROSS_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","DESIGNED_IN","REALISED","BENEFICIAL","LCR film/TV sector","Sufficient from LFO management data","primary","UNKNOWN","COMPLETE","CONTEMPORARY","COVID shut filming Mar-Jul 2020","HIGH","DESIGNER;DELIVERER;EVALUATOR;LEAD_CONSULTANT","METHOD_OUTPUT","M-G2-016","Documented output data; £1.788m of £2m capital deployed; richest quantitative evidence in post-2020 cohort","1.3-candidate","G2-BATCH-B"),
("C-G2-038","P22-LCRFILM","LCR Film Fund supported 455 indirect FTE jobs vs 280 target at average cost of £3930 per FTE (vs £6900 business case estimate)","DIRECT","","","The Fifth Sector","Liverpool Film Office","INTENDED","2021","BENEFICIAL","REPORTED","DESCRIPTIVE","MONETARY","INTENDED","ACROSS_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","DESIGNED_IN","REALISED","BENEFICIAL","LCR crew and productions","Sufficient from LFO data","primary","UNKNOWN","COMPLETE","CONTEMPORARY","COVID distorted investment profile","HIGH","DESIGNER;DELIVERER;EVALUATOR;LEAD_CONSULTANT","METHOD_OUTPUT","M-G2-016","Documented output data; 455 indirect FTE vs 280 target; cost per FTE below business case estimate","1.3-candidate","G2-BATCH-B"),
("C-G2-039","P22-LCRFILM","Development Fund deployed £173604 supporting 17 LCR companies and 43 LCR jobs vs targets of 12 companies and 30 jobs","DIRECT","","","The Fifth Sector","Liverpool Film Office","INTENDED","2021","BENEFICIAL","REPORTED","DESCRIPTIVE","MONETARY","INTENDED","WITHIN_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","DESIGNED_IN","REALISED","BENEFICIAL","LCR producers and writers","Sufficient from LFO data","primary","UNKNOWN","COMPLETE","CONTEMPORARY","NONE_FOUND_IN_REVIEW","HIGH","DESIGNER;DELIVERER;EVALUATOR;LEAD_CONSULTANT","METHOD_OUTPUT","M-G2-016","Documented output data; Development Fund exceeded company and job targets; seeded 7 pipeline projects","1.3-candidate","G2-BATCH-B"),
("C-G2-040","P22-LCRFILM","LFO moved from provider to partner by drawing in Fund Advisor external assessors/panel and broadcaster partners creating knowledge spillover","KNOWLEDGE","","","The Fifth Sector","Liverpool Film Office","INTENDED","2021","BENEFICIAL","REPORTED","DESCRIPTIVE","NON_MONETARY","UNINTENDED","ACROSS_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","UNCOMPENSATED","EMERGENT","REALISED","BENEFICIAL","LFO; LCR crew","Sufficient from evaluation findings","primary","UNKNOWN","COMPLETE","CONTEMPORARY","Skills gaps remain in HOD grades and entry-level roles","MEDIUM","DESIGNER;DELIVERER;EVALUATOR;LEAD_CONSULTANT","EFFECT","M-G2-016","Knowledge spillover observation; LFO partnership model; training places for 29 LCR individuals","1.3-candidate","G2-BATCH-B"),
("C-G2-041","P22-LCRFILM","Development Fund acts as seed capital creating option value for future indigenous pipeline with 7 seeded projects forecast at 7.8:1 leverage vs incoming 3.7:1","OPTION","STAGE_LEARN","","The Fifth Sector","Liverpool Film Office","INTENDED","UNKNOWN","BENEFICIAL","HYPOTHESIS","NOT_ASSESSED","MONETARY","INTENDED","WITHIN_ORG","WITHIN_SECTOR","WITHIN_AREA","WITHIN_CHAIN","COMPENSATED","DESIGNED_IN","FORECAST","BENEFICIAL","LCR indigenous producers","Pipeline forecasts not realised outcomes","primary","UNKNOWN","COMPLETE","CONTEMPORARY","Commercial success not guaranteed; recoupment figures are estimates","MEDIUM","DESIGNER;DELIVERER;EVALUATOR;LEAD_CONSULTANT","DESIGN","M-G2-016","Strategic option value; Development Fund as seed capital; indigenous vs incoming leverage differential; forecast not realised","1.3-candidate","G2-BATCH-B"),
]

new_rows = []
for c in claims:
    cid = c[0]
    if cid in existing_ids:
        print(f"SKIP {cid}")
        continue
    row = {h: c[i] if i < len(c) else "" for i, h in enumerate(header)}
    new_rows.append(row)
    print(f"ADD  {cid}: {c[1]}")

if new_rows:
    with open(CSV_PATH, "a", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=header)
        for row in new_rows:
            writer.writerow(row)
    print(f"\nAppended {len(new_rows)} claims (batch 1)")
print("Stage 4a complete.")
