#!/usr/bin/env python3
"""Stage 3: Register G2 post-2020 methods in 03_methods.csv."""
import csv, os

CSV_PATH = os.path.expanduser("~/Library/CloudStorage/GoogleDrive-iain@thefifthsector.co.uk/My Drive/Website 2026/spillover-toolkit/03_methods.csv")

with open(CSV_PATH, "r", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    header = reader.fieldnames
    existing_ids = {row["method_id"] for row in reader}

print(f"Existing method IDs: {len(existing_ids)}")

methods = [
    ("M-G2-010","P16-CICP","evaluation_design","PROPOSED","Mixed-methods contribution analysis; CBA; DiD; SRS microdata; LinkedIn/Meetup network mapping","Design four-phase evaluation framework for CICP and PEC","Evaluation approach document with ToC baselining and impact evaluation design","SRC-G2-011","Iain contributed sector/workforce mapping and methodology design via BOP; approach only not implemented; marginal claim","C-G2-024","REVIEWED","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("M-G2-011","P17-LCRCSU","creative_industries_mapping","APPLIED","BRES employment analysis; ONS business counts; LQ cluster analysis; Tech Nation digital sector definition","Produce evidence base for Leeds City Region Creative Scale Up bid","Evidence base with employment trends business counts LQ analysis and sector context","SRC-G2-012","Iain Bennett lead consultant; bid evidence not outcome evaluation; BRES ONS Nomisweb analysis","C-G2-025;C-G2-026","REVIEWED","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("M-G2-012","P18-GRIMSBY","cultural_participation_mapping","APPLIED","Audience data analysis (Taking Part Active People Active Lives); Mosaic profiling; stakeholder engagement; venue analysis","Map cultural participation baselines for Grimsby and recommend CDF programme","Phase 1 report with participation baselines venue analysis and programme recommendations","SRC-G2-013","Fifth Sector contributed mapping data; Magna Vitae authored; participation baselines from national surveys; no economic output data","C-G2-027","REVIEWED","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("M-G2-013","P19-LCRIMM","immersive_tech_sector_mapping","APPLIED","AI web search company database; LinkedIn workforce analysis; survey n=56; semi-structured interviews; case studies; benchmarking; SWOT","Map LCR immersive ecosystem and identify barriers and opportunities","Final report with 169 organisations mapped; survey; case studies; benchmarking; SWOT","SRC-G2-014","Iain Bennett as BOP author; cross-sector case studies (Draw and Code Kinicho VEC/Bentley); market forecasts from secondary sources","C-G2-028;C-G2-029;C-G2-030;C-G2-031","REVIEWED","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("M-G2-014","P20-SYMCA21","creative_industries_mapping","APPLIED","BRES via Nomisweb; IDBR; Companies House cleansed; FAME; Beauhurst; LinkedIn; DCMS GVA estimation; ONS productivity index","Map CCI scale and dynamics for South Yorkshire","Mapping report with 4000+ companies 31000 workforce; GVA estimates; business dynamics; skills pathways","SRC-G2-015","Fifth Sector lead with Curator Technologies and Morra; BRES undercounts freelancers; GVA uses generic ONS productivity index; creative growth paradox finding","C-G2-032;C-G2-033;C-G2-034","REVIEWED","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("M-G2-015","P21-MMUCCI","cci_positioning_audit","APPLIED","Semi-structured stakeholder interviews; desk-based website research; benchmarking of comparator institutions","Audit MMU CCI offer and recommend positioning improvements","Report with stakeholder findings; website audit; benchmarking; recommendations","SRC-G2-016","Fifth Sector lead; interviews Mar-Aug 2022; no turnover/GVA baselines; REF 2021 results; network gap findings","C-G2-035;C-G2-036","REVIEWED","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("M-G2-016","P22-LCRFILM","film_fund_evaluation","APPLIED","Desk review of project data; LFO management/financial data analysis; recoupment projections; scenario planning; EDI monitoring; process evaluation","Evaluate LCR Film Fund delivery and propose scenario options","Interim evaluation with output data; recoupment scenarios; pipeline analysis; recommendations","SRC-G2-017","Iain Bennett for Liverpool Film Office; £6.76 leverage; 455 indirect FTE; recoupment projections are estimates; Development Fund seeded 7 pipeline projects","C-G2-037;C-G2-038;C-G2-039;C-G2-040;C-G2-041","REVIEWED","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("M-G2-017","P23-DERBY","feasibility_study","APPLIED","Online survey n=17; in-depth interview with Liverpool Film Office; ScreenSkills discussions; case material from Yorkshire/NE","Assess feasibility of joint Derby and Derbyshire Film Office","Feasibility study with survey findings; Liverpool comparator; job descriptions; recommendations","SRC-G2-018","Fifth Sector lead; survey n=17 explicitly not quantitative evidence base; no local baseline; Liverpool comparator; 2 FTE staged start-up design","C-G2-042","REVIEWED","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("M-G2-018","P24-SYMCACGP","creative_industries_mapping","APPLIED","BRES; LinkedIn; IDBR; Companies House; FAME; Beauhurst; DCMS GVA; ONS productivity index; LQ analysis; training provision mapping","Map CCI for SYMCA and inform Create Growth and Arts Culture Heritage strategy","Final report with 4025 companies 31000 workforce; GVA up to £2bn; 1013 courses; 5 apprenticeships; creative growth paradox","SRC-G2-019","Fifth Sector lead with Curator Technologies; extends P20-SYMCA21; GVA modelled using generic productivity index; creative growth paradox","C-G2-043;C-G2-044;C-G2-045;C-G2-046","REVIEWED","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("M-G2-019","P25-LANCGP","bid_development","APPLIED","Companies House via Beauhurst; LinkedIn via Curator Technologies; consultation with partners; programme design and costing","Develop DCMS Create Growth bid for Lancashire","Full application with evidence base; 4 hub designs; £1.275m budget; programme architecture","SRC-G2-020","Fifth Sector cited as data source; grant application not outcome report; 4500 businesses 36000 jobs; Pennine Originals spillover into aerospace/automotive","C-G2-047;C-G2-048","REVIEWED","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("M-G2-020","P26-WSBH","creative_industries_strategy","APPLIED","BRES 2021; IDBR; Companies House via Beauhurst; LinkedIn; Nesta cluster definitions; skills mapping; consultation round tables; business survey","Map CI and develop strategy for West Sussex Brighton Hove Lewes","Strategy with 10225 companies 54428 workforce; 6 tables; 3-phase investment plan; Createch strengths","SRC-G2-021","Fifth Sector lead with Curator Technologies and Morra; FuseBox24; Creative Assembly and Red River as anchor investors; Digital Catapult Brighton","C-G2-049;C-G2-050;C-G2-051","REVIEWED","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("M-G2-021","P27-WAKECDF","cultural_development_fund_evaluation","APPLIED","Desk/data analysis (ONS BRES LinkedIn DCMS monitoring); case studies; qualitative interviews; theory of change; value-for-money assessment","Evaluate CDF programme delivery outputs and legacy","Evaluation report with 14 tables; financial analysis; ToC; case studies; network analysis","SRC-G2-022","Iain Bennett and Steve Hunt for Wakefield Council; £4.38m CDF £22.03m total; CCI employment +32%; GVA +79%; Creative Wakefield +458%; CoSTAR secured; INTERNAL INCONSISTENCY: 120 vs 160 FTE","C-G2-052;C-G2-053;C-G2-054;C-G2-055;C-G2-056;C-G2-057;C-G2-058","REVIEWED","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("M-G2-022","P28-CALDER","creative_industries_mapping","APPLIED","ONS/IDBR 2015-2023; BRES 2022; Companies House via Beauhurst; LinkedIn July 2023; LQ analysis; music deep dive; course/qualification audit; consultation","Map CCI for Calderdale to inform investment planning 2024-2029","Research report with 18 tables; 655 ONS firms 880 Beauhurst; 2360 BRES; 7375 LinkedIn; music deep dive; Cultural Compact proposed","SRC-G2-023","Fifth Sector prime; LinkedIn not directly comparable to BRES; small round-table sample n=28; Screen Yorkshire Connected Campus","C-G2-059;C-G2-060;C-G2-061","REVIEWED","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("M-G2-023","P29-SOLENTCGP","bid_development","APPLIED","Companies House via Beauhurst; IDBR/Nomisweb; BOP cluster data; Lightcast employment/GVA; Oxford Economics; consultation; eligibility modelling","Develop CGP expansion bid for Solent","Draft application with market evidence; 3 cohort designs; Solent Creative Investment Framework","SRC-G2-024","Fifth Sector appointed for market awareness research; DRAFT application; 4510 businesses 40000 jobs; Createch maritime/aerospace spillovers","C-G2-062;C-G2-063","REVIEWED","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("M-G2-024","P30-HEREFORD","culture_strategy_review","APPLIED","Stakeholder consultation 100+; skills analysis; strategic review of goals/pledges/actions; comparator analysis (Cornwall Cumbria Lincolnshire); ONS/DCMS data","Review 10-year cultural strategy at mid-point","Review report with progress assessment; comparator analysis; 5 strategic priorities","SRC-G2-025","Iain confirmed lead consultant; 590 official businesses 4000+ LinkedIn; 56% graduate leakage; rural creative economy; fragmented ecosystem","C-G2-064;C-G2-065","REVIEWED","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("M-G2-025","P31-PRODPARK","gva_data_analysis","APPLIED","LinkedIn industry codes mapped to BRES SIC07; employment cross-tabulation","Provide employment data for Production Park area","Data table with LinkedIn/BRES mapping; no narrative","SRC-G2-026","Data fragment only; BRES 2022 columns empty; incomplete; supplements P27-WAKECDF","C-G2-066","REVIEWED","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("M-G2-026","P32-SURREY","creative_corridor_strategy","APPLIED","Sector consultation 6 months; mapping evidence; comparator analysis (European and North American regions); economic modelling; investment appraisal","Develop creative corridor strategy and investment framework","Strategy with £7.2bn value; 17000 companies; 115000 workforce; 4 recommendations; £3-4m investment ask","SRC-G2-027","Iain confirmed lead consultant; aerospace-to-screen spillover (Farnborough); CoSTAR/Games Innovation Zone; investment returns are modelled forecasts","C-G2-067;C-G2-068;C-G2-069","REVIEWED","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("M-G2-027","P33-LCRMUS","music_economy_mapping","APPLIED","Four-tier workforce model; firmographic analysis (Companies House DataCity Charity Commission CIC); LinkedIn; platform data (MusicSeen Instagram Spotify PRS); survey n=70; SNA of 272 businesses; Type II multiplier 1.92; LQ analysis; sensitivity analysis","Map LCR music economy scale and dynamics and identify growth levers","Final report with 38 tables; 14370 headcount 7215 FTE; £405.9m direct GVA £779.8m total; SNA; growth scenarios; 4 growth levers","SRC-G2-028","Fifth Sector/Unscrambled with UoL IPM; four-tier workforce model is methodological innovation; SNA of 272 businesses; Tier 4 data quality low; LinkedIn coverage ~45%; concentration risk","C-G2-070;C-G2-071;C-G2-072;C-G2-073;C-G2-074","REVIEWED","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("M-G2-028","P34-SOLENTHANTS","creative_industries_mapping","APPLIED","ONS IDBR; BRES 2023; DataCity; LinkedIn April 2025; DCMS GVA; ONS regional productivity; LQ analysis; HDBSCAN spatial clustering; Creative Trident supply-chain framing","Map CI for Solent and Hampshire CA","Mapping report with 11 tables; £5.25bn GVA reconciled; 39980 BRES 80511 LinkedIn; 7530 IDBR 11420 DataCity; HDBSCAN clustering","SRC-G2-029","Fifth Sector/Unscrambled; DCMS top-down £6.9bn almost certainly overestimate; LinkedIn over-represents advertising/design; 31% IT contraction; HDBSCAN caveat re accountants","C-G2-075;C-G2-076;C-G2-077","REVIEWED","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
]

new_rows = []
for m in methods:
    mid = m[0]
    if mid in existing_ids:
        print(f"SKIP {mid}")
        continue
    row = {h: m[i] if i < len(m) else "" for i, h in enumerate(header)}
    new_rows.append(row)
    print(f"ADD  {mid}: {m[2]}")

if new_rows:
    with open(CSV_PATH, "a", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=header)
        for row in new_rows:
            writer.writerow(row)
    print(f"\nAppended {len(new_rows)} methods")
print("Stage 3 complete.")
