#!/usr/bin/env python3
"""Stage 2: Register 19 post-2020 G2 sources in 02_sources.csv."""
import csv
import os

CSV_PATH = os.path.expanduser("~/Library/CloudStorage/GoogleDrive-iain@thefifthsector.co.uk/My Drive/Website 2026/spillover-toolkit/02_sources.csv")

with open(CSV_PATH, "r", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    header = reader.fieldnames
    existing_ids = {row["source_id"] for row in reader}

print(f"Existing source IDs: {len(existing_ids)}")

sources = [
    ("SRC-G2-011","P16-CICP","CICP evaluation approach final","evaluation_approach","Frontier Economics / BOP Consulting","2020","canonical/P16-CICP/ProJ 1.1- approach-final.docx","entire approach document","internal_only","COMPLETE","primary","CICP-FAM","84 paras 1 table; evaluation approach design not outcome report; Fifth Sector contributed mapping and methodology via BOP; marginal claim; Iain confirmed 2026-09-11","Archive projects/Google project folders/2020/UKRI AHRC - Creative Industries Clusters Progr - (2020-2024)/ProJ 1.1- approach-final.docx","extracted_text/SRC-G2-011_v1_full.txt","CANONICAL","Evaluation approach document; not outcome report","REVIEWED","python-docx","full","1 table; headers/footers not captured","original DOCX","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("SRC-G2-012","P17-LCRCSU","Leeds City Region Creative Scale Up v2.0","report","Iain Bennett / The Fifth Sector","2020-07-30","canonical/P17-LCRCSU/200730 Leeds CIty Region Creative Scale Up v2.0.docx","full report","internal_only","COMPLETE","primary","LCRCSU-FAM","200 paras 1 table; Iain Bennett lead consultant (line 198); bid evidence base not outcome evaluation; BRES ONS LQ analysis; Channel 4 relocation context","Archive projects/2020 Projects/2020 Leeds City Region Creative Scale Up/200730 Leeds CIty Region Creative Scale Up v2.0.docx","extracted_text/SRC-G2-012_v1_full.txt","CANONICAL","Bid evidence base; Iain Bennett lead consultant","REVIEWED","python-docx","full","1 table; headers/footers not captured","original DOCX","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("SRC-G2-013","P18-GRIMSBY","NELC Phase 1 Report FINAL","report_pdf","Magna Vitae","2020","canonical/P18-GRIMSBY/NELC Phase 1 Report FINAL.pdf","full report","internal_only","COMPLETE","primary","GRIMSBY-FAM","60 pages; Magna Vitae authored; Fifth Sector contributed mapping data (Iain confirmed 2026-09-11); participation baselines from national surveys; no economic output data; design propositions not outcomes","Archive projects/2020 Projects/2020 Grimsby CCI/NELC Phase 1 Report FINAL.pdf","extracted_text/SRC-G2-013_v1_full.txt","CANONICAL","Magna Vitae report; Fifth Sector data contributor","REVIEWED","PyPDF2","full","60 pages; images/tables not captured","original PDF","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("SRC-G2-014","P19-LCRIMM","LCR Immersive Sector final report May 2020","report_pdf","Iain Bennett / Marta Moretto / BOP Consulting","2020-05","canonical/P19-LCRIMM/Liverpool City Region Immersive Sector final report May 2020.pdf","full report","internal_only","COMPLETE","primary","LCRIMM-FAM","57 pages; Iain Bennett as BOP author (line 18); 169 organisations mapped; survey n=56; cross-sector case studies; work began 2019 delivered May 2020; post-2020 replacement per Iain","Archive projects/2019 Projects/2019 LCR Growth Company Immersive tech/Reporting/Liverpool City Region Immersive Sector final report May 2020.pdf","extracted_text/SRC-G2-014_v1_full.txt","CANONICAL","Final report; Iain Bennett as BOP author","REVIEWED","PyPDF2","full","57 pages; images/tables not captured","original PDF","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("SRC-G2-015","P20-SYMCA21","SYMCA Cultural and Creative Industries 1.1","report","The Fifth Sector","2022-06-08","canonical/P20-SYMCA21/200608 SYMCA Cultural and Creative Industries 1.1.docx","full report","internal_only","COMPLETE","primary","SYMCA21-FAM","324 paras; Fifth Sector lead with Curator Technologies and Morra; BRES LinkedIn IDBR Companies House FAME Beauhurst; 4000+ companies 31000 workforce; creative growth paradox","Archive projects/2021 Projects/2021 SYMCA CCI research/200608 SYMCA Cultural and Creative Industries 1.1.docx","extracted_text/SRC-G2-015_v1_full.txt","CANONICAL","Fifth Sector lead consultant","REVIEWED","python-docx","full","headers/footers not captured","original DOCX","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("SRC-G2-016","P21-MMUCCI","Man Met CCI report v2","report","The Fifth Sector","2022-10-14","canonical/P21-MMUCCI/221014 Man Met CCI report v2.docx","full report","internal_only","COMPLETE","primary","MMUCCI-FAM","521 paras; Fifth Sector lead (www.thefifthsector.co.uk line 24); stakeholder interviews Mar-Aug 2022; desk research; benchmarking; REF 2021; network gap findings","Archive projects/2021 Projects/2021 MMU CCI/Reporting/221014 Man Met CCI report v2.docx","extracted_text/SRC-G2-016_v1_full.txt","CANONICAL","Fifth Sector lead consultant","REVIEWED","python-docx","full","headers/footers not captured","original DOCX","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("SRC-G2-017","P22-LCRFILM","Liverpool Production Fund Interim Evaluation draft report","evaluation_report","Iain Bennett / The Fifth Sector","2021-02-04","canonical/P22-LCRFILM/210204 Liverpool Production Fund Interim Evaluation draft report.docx","full evaluation","internal_only","COMPLETE","primary","LCRFILM-FAM","232 paras 5 tables; Iain Bennett of The Fifth Sector for Liverpool Film Office (lines 225-231); £6.76 leverage; 455 indirect FTE; Development Fund 7 pipeline projects; recoupment projections are estimates; richest documented output data","Archive projects/2020 Projects/2020 Liverpool Film Fund evaluation/Reporting/210204 Liverpool Production Fund Interim Evaluation draft report.docx","extracted_text/SRC-G2-017_v1_full.txt","CANONICAL","Interim evaluation; Fifth Sector prime","REVIEWED","python-docx","full","5 tables; headers/footers not captured","original DOCX","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("SRC-G2-018","P23-DERBY","Derby(s) Film Office feasibility study","feasibility_study","The Fifth Sector","2022-08-09","canonical/P23-DERBY/220809 Derby(s) Film Office feasibility study.pdf","full study","internal_only","COMPLETE","primary","DERBY-FAM","27 pages; Fifth Sector lead consultant; survey n=17; Liverpool Film Office comparator; no local baseline; 2 FTE start-up design proposition","Archive projects/2022 Projects/2022 Derby Screen Agency/220809 Derby(s) Film Office feasibility study.pdf","extracted_text/SRC-G2-018_v1_full.txt","CANONICAL","Feasibility study; Fifth Sector prime","REVIEWED","PyPDF2","full","27 pages; images/tables not captured","original PDF","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("SRC-G2-019","P24-SYMCACGP","SYMCA Cultural and Creative Industries final report","report","The Fifth Sector","2022","canonical/P24-SYMCACGP/SYMCA Cultural and Creative Industries final report.docx","full report","internal_only","COMPLETE","primary","SYMCACGP-FAM","370 paras 4 tables; Fifth Sector lead with Curator Technologies; 4025 companies 31000 workforce; GVA up to £2bn; creative growth paradox; 1013 courses; extends P20-SYMCA21","Archive projects/2022 Projects/2022 SYMCA Create Growth/2022 SYMCA CGP Reporting/SYMCA Cultural and Creative Industries final report.docx","extracted_text/SRC-G2-019_v1_full.txt","CANONICAL","Fifth Sector lead consultant","REVIEWED","python-docx","full","4 tables; headers/footers not captured","original DOCX","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("SRC-G2-020","P25-LANCGP","Lancashire Create Growth Programme FINAL","grant_application","Lancashire LEP / Fifth Sector data","2022-09","canonical/P25-LANCGP/Lancashire Create Growth Programme FINAL.pdf","full application","internal_only","COMPLETE","primary","LANCGP-FAM","42 pages; Fifth Sector cited as data source (lines 197 1427 1430); grant application not outcome report; 4500 businesses 36000 jobs; 4 hubs; £1.275m budget; Pennine Originals spillover into aerospace/automotive","Archive projects/2022 Projects/2022 Lancashire Create Growth/Lancashire Create Growth Programme FINAL.pdf","extracted_text/SRC-G2-020_v1_full.txt","CANONICAL","Grant application; Fifth Sector data contributor","REVIEWED","PyPDF2","full","42 pages; images/tables not captured","original PDF","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("SRC-G2-021","P26-WSBH","West Sussex Brighton Hove Lewes CI v2","strategy","The Fifth Sector","2023-04-21","canonical/P26-WSBH/230421 West Sussex Brighton Hove Lewes CI v2.docx","full strategy","internal_only","COMPLETE","primary","WSBH-FAM","607 paras 6 tables; Fifth Sector lead with Curator Technologies and Morra; 10225 companies 54428 workforce; BRES 2021; Createch; Digital Catapult Brighton; FuseBox24; 3-phase investment plan","Archive projects/2022 Projects/2022 West Sussex Brighton Hove Lewes/2022 West Sussex Reporting/230421 West Sussex Brighton Hove Lewes CI v2.docx","extracted_text/SRC-G2-021_v1_full.txt","CANONICAL","Fifth Sector lead consultant","REVIEWED","python-docx","full","6 tables; headers/footers not captured","original DOCX","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("SRC-G2-022","P27-WAKECDF","CDF Evaluation FINAL","evaluation_report","Iain Bennett / Steve Hunt / The Fifth Sector","2025-09-29","canonical/P27-WAKECDF/250929 CDF Evaluation FINAL.docx","full evaluation","internal_only","COMPLETE","primary","WAKECDF-FAM","556 paras 14 tables; Iain Bennett and Steve Hunt for Wakefield Council (line 11); £4.38m CDF £22.03m total; CCI employment +32%; GVA +79%; Creative Wakefield +458%; CoSTAR secured; 10 new-to-market products; INTERNAL INCONSISTENCY: 120 vs 160 FTE","Archive projects/2025 Projects/2022 Wakefield CDF - Local Programme Evaluation/2024 CDF2 Reporting/250929 CDF Evaluation FINAL.docx","extracted_text/SRC-G2-022_v1_full.txt","CANONICAL","Final evaluation; Fifth Sector prime","REVIEWED","python-docx","full","14 tables; headers/footers not captured","original DOCX","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("SRC-G2-023","P28-CALDER","Calderdale CCI report final","report","The Fifth Sector","2023-12-19","canonical/P28-CALDER/231219 Calderdale CCI report final.docx","full report","internal_only","COMPLETE","primary","CALDER-FAM","639 paras 18 tables; Produced by The Fifth Sector Limited (line 9); 655 ONS firms 880 Beauhurst; 2360 BRES; 7375 LinkedIn; music deep dive; Screen Yorkshire; Cultural Compact proposed","Archive projects/2023 Projects/2023 Calderdale/2023 Calderdale reporting/231219 Calderdale CCI report final.docx","extracted_text/SRC-G2-023_v1_full.txt","CANONICAL","Fifth Sector prime","REVIEWED","python-docx","full","18 tables; headers/footers not captured","original DOCX","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("SRC-G2-024","P29-SOLENTCGP","CGP Expansion FullApplication Form_Solent_DRAFT","grant_application_draft","Solent LEP / The Fifth Sector","2023","canonical/P29-SOLENTCGP/CGP Expansion FullApplication Form_Solent_DRAFT.docx","full draft application","internal_only","COMPLETE","primary","SOLENTCGP-FAM","59 paras 6 tables; Fifth Sector appointed for market awareness research (line 191); DRAFT application; 4510 businesses 40000 jobs £1.5bn GVA; Createch maritime/aerospace spillovers; Solent Creative Investment Framework","Archive projects/2023 Projects/2023 Solent CGP/2023 Solent CGP Proposal/CGP Expansion FullApplication Form_Solent_DRAFT.docx","extracted_text/SRC-G2-024_v1_full.txt","DRAFT","Draft application; Fifth Sector data contributor","REVIEWED","python-docx","full","6 tables; headers/footers not captured","original DOCX","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("SRC-G2-025","P30-HEREFORD","Herefordshire Culture Strategy Review","strategy_review","The Fifth Sector","2024-06-17","canonical/P30-HEREFORD/260617 Herefordshire Culture Strategy Review.docx","full review","internal_only","COMPLETE","primary","HEREFORD-FAM","225 paras; Iain confirmed lead consultant 2026-09-11; 590 official businesses 4000+ LinkedIn; 100 courses; 56% graduate leakage; rural creative economy; fragmented ecosystem; cultural compact proposed","Archive projects/2024 Projects/2024 Herefordshire/2024 Herefordshire reporting/260617 Herefordshire Culture Strategy Review.docx","extracted_text/SRC-G2-025_v1_full.txt","CANONICAL","Fifth Sector lead consultant confirmed by Iain","REVIEWED","python-docx","full","headers/footers not captured","original DOCX","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("SRC-G2-026","P31-PRODPARK","Production Park GVA data","data_fragment","The Fifth Sector","2024-07-19","canonical/P31-PRODPARK/240719 Production Park GVA data.docx","data table only","internal_only","COMPLETE","primary","PRODPARK-FAM","11 paras 1 table; data fragment only; LinkedIn codes mapped to BRES SIC07; BRES 2022 columns empty; no narrative; no spillover evidence; supplements P27-WAKECDF","Archive projects/2024 Projects/2024 Production Park GVA/240719 Production Park GVA data.docx","extracted_text/SRC-G2-026_v1_full.txt","SUPPLEMENTARY","Data fragment; incomplete; supplements Wakefield CDF","REVIEWED","python-docx","full","1 table; BRES columns empty","original DOCX","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("SRC-G2-027","P32-SURREY","Human Rewrite IB CLEAN","strategy","The Fifth Sector","2025-08-18","canonical/P32-SURREY/250818 Human Rewrite IB CLEAN.docx","full strategy","internal_only","COMPLETE","primary","SURREY-FAM","212 paras; Iain confirmed lead consultant 2026-09-11; £7.2bn annual value; 17000 companies; 115000 workforce; 12% growth; 43% freelance; aerospace-to-screen spillover; CoSTAR/Games Innovation Zone; £3-4m investment ask","Archive projects/2024 Projects/2024 Surrey+ Corridor/2025 Surrey+ Reporting/250818 Human Rewrite IB CLEAN.docx","extracted_text/SRC-G2-027_v1_full.txt","CANONICAL","Fifth Sector lead consultant confirmed by Iain","REVIEWED","python-docx","full","headers/footers not captured","original DOCX","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("SRC-G2-028","P33-LCRMUS","LCR_Music_Economy_Final_Report","report","The Fifth Sector / Unscrambled.world / University of Liverpool IPM","2026-02-22","canonical/P33-LCRMUS/260222 LCR_Music_Economy_Final_Report.docx","full report","internal_only","COMPLETE","primary","LCRMUS-FAM","650 paras 38 tables; Fifth Sector/Unscrambled with UoL IPM (lines 13-15); four-tier workforce model; 14370 headcount 7215 FTE; £405.9m direct GVA £779.8m total; SNA of 272 businesses; 335 businesses 621 venues; Adlib cross-sector; £1bn by 2035 target","Archive projects/2025 Projects/2025 Liverpool Music/2025 Liverpool Music reporting/260222 LCR_Music_Economy_Final_Report.docx","extracted_text/SRC-G2-028_v1_full.txt","CANONICAL","Fifth Sector prime with Unscrambled and UoL IPM","REVIEWED","python-docx","full","38 tables; headers/footers not captured","original DOCX","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
    ("SRC-G2-029","P34-SOLENTHANTS","Solent and Hampshire CA CI Mapping","report","The Fifth Sector / Unscrambled","2025-07-18","canonical/P34-SOLENTHANTS/250718 Solent and Hampshire CA CI Mapping.docx","full report","internal_only","COMPLETE","primary","SOLENTHANTS-FAM","354 paras 11 tables; Prepared by The Fifth Sector Limited (line 7); £5.25bn GVA reconciled; 39980 BRES 80511 LinkedIn; 7530 IDBR 11420 DataCity; HDBSCAN clustering; 31% IT contraction; freelancers as knowledge transfer agents","Archive projects/2025 Projects/2025 Solent and Hampshire CI/2025 Solent and Hants Reporting/250718 Solent and Hampshire CA CI Mapping.docx","extracted_text/SRC-G2-029_v1_full.txt","CANONICAL","Fifth Sector prime with Unscrambled","REVIEWED","python-docx","full","11 tables; headers/footers not captured","original DOCX","Devin","2026-09-11","1.3-candidate","G2-BATCH-B"),
]

new_rows = []
for s in sources:
    sid = s[0]
    if sid in existing_ids:
        print(f"SKIP {sid}")
        continue
    row = {h: s[i] if i < len(s) else "" for i, h in enumerate(header)}
    new_rows.append(row)
    print(f"ADD  {sid}: {s[2]}")

if new_rows:
    with open(CSV_PATH, "a", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=header)
        for row in new_rows:
            writer.writerow(row)
    print(f"\nAppended {len(new_rows)} sources to 02_sources.csv")
print("Stage 2 complete.")
