#!/usr/bin/env python3
"""Figure check: read-only. Run from the toolkit root.  python3 tools/figure_check.py

For every claim, takes the numbers in `precise_proposition` and looks for each in the extracted text of the sources
its evidence links cite (extracted_text/, including appended tables). A figure found in no cited source is reported as
UNMATCHED. This is a screen, not a verdict: rounded figures, derived figures (ratios, sums), figures stated in words
and sources with no extract will all show as unmatched. It exists to rank AGENTS.md spot checks (high-risk numerical
claims first), never to mark a claim verified.

Output: figure_check_report.md (derived; claims with unmatched figures, grouped by project, with the reason class).
"""
import csv, collections, os, re

def rows(p):
    with open(p, newline='', encoding='utf-8') as f:
        return list(csv.DictReader(f))

NUM = re.compile(r'(?<![A-Za-z0-9])(\d[\d,]*\.?\d*)')

def numbers(text):
    out = set()
    for m in NUM.finditer(text):
        raw = m.group(1).rstrip('.').replace(',', '')
        if not raw or raw in ('0', '1'): continue
        if re.fullmatch(r'(19|20)\d\d', raw): continue          # years
        if re.fullmatch(r'\d{2}/\d{2}(/\d{2})?', m.group(1)): continue
        out.add(raw)
    return out

def main():
    C = rows('04_claims.csv'); E = rows('05_evidence_links.csv'); S = {s['source_id']: s for s in rows('02_sources.csv')}
    ev = collections.defaultdict(set)
    for e in E: ev[e['claim_id']].add(e['source_id'])
    cache = {}
    def src_numbers(sid):
        if sid in cache: return cache[sid]
        loc = S.get(sid, {}).get('derived_location', '')
        if loc.startswith('extracted_text/') and os.path.exists(loc):
            t = open(loc, encoding='utf-8', errors='replace').read()
            cache[sid] = numbers(t) | {x.replace(',', '') for x in re.findall(r'\d[\d,]*\.\d+|\d[\d,]*', t)}
        else: cache[sid] = None
        return cache[sid]
    res = []; noext = 0; nofig = 0; ok = 0
    for c in C:
        nums = numbers(c['precise_proposition'])
        if not nums: nofig += 1; continue
        srcs = ev.get(c['claim_id'], set())
        avail = [src_numbers(s) for s in srcs]; avail = [a for a in avail if a is not None]
        if not avail: noext += 1; res.append((c, sorted(nums), None, 'NO_EXTRACT')); continue
        found = set().union(*avail)
        miss = sorted(n for n in nums if n not in found and n.lstrip('0') not in found)
        if miss: res.append((c, sorted(nums), miss, 'UNMATCHED'))
        else: ok += 1
    risky = re.compile(r'GVA|FTE|multiplier|leverage|£|%|jobs|turnover', re.I)
    L = ['# Figure check (derived, read-only)', '',
         'Generated by `tools/figure_check.py`. A screen to rank spot checks, not a verification. Rounded, derived or spelled-out figures and sources without an extract will appear as unmatched.', '',
         '- Claims: %d. With no figure in the proposition: %d. All figures found in a cited source extract: %d. Unmatched figure(s): %d. Cited sources have no extract: %d.' % (len(C), nofig, ok, sum(1 for r in res if r[3] == 'UNMATCHED'), noext), '',
         '## Unmatched figures, high-risk claims first (GVA, FTE, multiplier, leverage, £, %, jobs, turnover)', '']
    um = [r for r in res if r[3] == 'UNMATCHED']
    um.sort(key=lambda r: (0 if risky.search(r[0]['precise_proposition']) else 1, r[0]['project_id'], r[0]['claim_id']))
    for c, nums, miss, kind in um:
        L.append('- %s (%s, %s): figures not found: %s | %s' % (c['claim_id'], c['project_id'], c['claim_type'], ', '.join(miss), c['precise_proposition'][:110]))
    L += ['', '## Claims whose cited sources have no extract (cannot be screened)', '']
    for c, nums, miss, kind in [r for r in res if r[3] == 'NO_EXTRACT'][:80]:
        L.append('- %s (%s): figures %s' % (c['claim_id'], c['project_id'], ', '.join(nums[:5])))
    open('figure_check_report.md', 'w', encoding='utf-8').write('\n'.join(L) + '\n')
    print(L[4]); print('unmatched claims:', len(um), '| no-extract claims:', noext)

if __name__ == '__main__':
    main()
