#!/usr/bin/env python3
"""Method view: read-only. Run from the toolkit root.  python3 tools/method_view.py [--family EVALUATION]

For each method statement in method_statements/ shows a lift badge, plain-English flags in three tiers
(BLOCKER, CAUTION, INFO, each with who acts), the applications the statement rests on (project, contracting
arrangement, citation status, method status) and the claims behind it.

Disclosure gate (method package, lane review 26/10/08): for any statement whose disclosure_status is not CLEARED the
view shows claim IDs and types only and withholds claim wording and all figures, so cleared-nothing figures cannot be
lifted from the view. Staleness, link and format checks are new flags only; no existing check is changed.
Nothing is ranked. Output: method_views/statements.md (derived).
"""
import argparse, csv, glob, os, re

REQUIRED = ['statement_id', 'name', 'family', 'status', 'evidence_class', 'applications', 'claims', 'our_role',
            'disclosure_status', 'as_at_date', 'evidence_review_date', 'drafted_by', 'reviewed_by', 'next_action']

def rows(p):
    with open(p, newline='', encoding='utf-8') as f:
        return list(csv.DictReader(f))

def header(path):
    d = {}; bad = []; inside = False; n = 0
    for line in open(path, encoding='utf-8'):
        line = line.rstrip('\n')
        if line.strip() == '---': inside = not inside; n += 1; continue
        if inside and line.strip():
            m = re.match(r'^([a-z_]+): (.*)$', line)
            if m: d[m.group(1)] = m.group(2)
            else: bad.append(line[:60])
    if n < 2: bad.append('header rules (---) missing or unbalanced')
    return d, bad

def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--family')
    ap.add_argument('--requirements', help='tender id; adds a table of which statements cover which questions (tender_requirements/<id>.md, item coverage)')
    ap.add_argument('--stale-days', type=int, help='optional: flag a statement whose as_at_date is older than this many days (no default; Iain sets the threshold)')
    a = ap.parse_args()
    meth = {m['method_id']: m for m in rows('03_methods.csv')}
    proj = {p['project_id']: p for p in rows('01_projects.csv')}
    claims = {c['claim_id']: c for c in rows('04_claims.csv')}
    L = ['# Method statements (derived, read-only)', '',
         'Generated by `tools/method_view.py`. Not a ranking. Claim wording and figures are shown only for statements whose disclosure status is CLEARED. Wording is capped at the evidence class of the claims behind a statement.', '']
    for path in sorted(glob.glob('method_statements/MS-*.md')):
        h, bad = header(path)
        if a.family and h.get('family') != a.family: continue
        B = []; C = []; I = []
        for line in bad: B.append('Header line is malformed and was skipped: "%s". Owner: Devin.' % line)
        for k in REQUIRED:
            if not h.get(k): B.append('Required field "%s" is missing. Owner: Devin.' % k)
        st = h.get('status', ''); disc = h.get('disclosure_status', '')
        if st == 'SUPERSEDED': B.append('This statement is superseded; do not use it as current.')
        if st == 'CURRENT' and (not h.get('reviewed_by') or h.get('reviewed_by') == 'pending'):
            B.append('Marked CURRENT but nobody has reviewed it. Only Iain can set CURRENT. Owner: Iain.')
        if st == 'DRAFT': C.append('Draft: not approved by Iain yet. Owner: Iain.')
        if disc != 'CLEARED': B.append('Cannot be lifted into a bid yet: disclosure is "%s". %s Owner: Iain.' % (disc or 'missing', h.get('next_action', '')))
        if h.get('lift_into_case_study', '').startswith('NO'): B.append('Not to be used as a case study.')
        elif h.get('lift_into_case_study'): C.append('Case-study use limited: %s.' % h['lift_into_case_study'].replace('_', ' ').lower())
        if h.get('evidence_class', '').startswith('DESIGN_ONLY'): C.append('Design only: say "contributed to the design of", never "delivered".')
        L += ['## %s %s' % (h.get('statement_id', os.path.basename(path)), h.get('name', '')), '',
              '- Family: %s. Evidence class: %s. Status: %s.' % (h.get('family', ''), h.get('evidence_class', ''), st),
              '- Our role: %s' % h.get('our_role', ''), '', '| Application | Project | Contracting | Citation | Method status |', '|---|---|---|---|---|']
        apps = [x for x in h.get('applications', '').split(';') if x]
        if not apps: B.append('No application is recorded for this statement. Owner: Devin.')
        for mid in apps:
            m = meth.get(mid)
            if not m: L.append('| %s | not found | | | |' % mid); B.append('Method row %s does not exist. Owner: Devin.' % mid); continue
            p = proj.get(m['project_id'], {})
            arr = p.get('contracting_role', '') or 'not recorded'
            if p.get('prime_contractor') and arr not in ('PRIME', 'DIRECT'): arr += ' to ' + p['prime_contractor']
            if arr == 'not recorded': C.append('Contracting role not recorded for %s (%s): the statement cannot state our arrangement. Owner: Iain.' % (p.get('canonical_name', m['project_id']), m['project_id']))
            if m.get('statement_id', '') != h.get('statement_id', ''):
                C.append('Method row %s is not linked back to this statement in 03_methods.csv (its statement_id is "%s"). Owner: Devin.' % (mid, m.get('statement_id', '')))
            if m['method_status'] == 'SUPERSEDED': B.append('Method row %s is superseded.' % mid)
            elif m['method_status'] != 'APPLIED': C.append('Method row %s is %s, not applied.' % (mid, m['method_status']))
            if p.get('client_accepted') not in ('Y',): I.append('Client acceptance not recorded as yes for %s.' % p.get('canonical_name', m['project_id']))
            L.append('| %s | %s (%s) | %s | %s | %s |' % (mid, p.get('canonical_name', m['project_id']), m['project_id'], arr, p.get('citation_status', ''), m['method_status']))
        if not h.get('evidence_review_date'): C.append('No evidence review date recorded.')
        newest = max([meth[x].get('review_date', '') for x in apps if x in meth and re.match(r'^\d\d/\d\d/\d\d$', meth[x].get('review_date', ''))] or [''])
        if h.get('evidence_review_date') and newest and newest > h['evidence_review_date']: C.append('A linked method row was reviewed on %s, after this statement\'s evidence review date (%s): re-check the statement. Owner: Devin.' % (newest, h['evidence_review_date']))
        if a.stale_days and re.match(r'^\d\d/\d\d/\d\d$', h.get('as_at_date', '')):
            import datetime
            d = datetime.datetime.strptime(h['as_at_date'], '%y/%m/%d')
            if (datetime.datetime.now() - d).days > a.stale_days: C.append('Statement is as at %s, more than %d days old. Owner: Iain.' % (h['as_at_date'], a.stale_days))
        L += ['', 'Claims behind it' + ('' if disc == 'CLEARED' else ' (wording and figures withheld: disclosure not cleared)') + ':', '']
        for cid in [x for x in h.get('claims', '').split(';') if x]:
            c = claims.get(cid)
            if not c: L.append('- %s: NOT FOUND' % cid); B.append('Claim %s does not exist. Owner: Devin.' % cid); continue
            if c.get('review_status') != 'REVIEWED': I.append('Claim %s has not been spot-checked (review status %s).' % (cid, c.get('review_status')))
            L.append('- %s (%s)%s' % (cid, c['claim_type'], (': ' + c['precise_proposition']) if disc == 'CLEARED' else ''))
        liftok = not B
        L += ['', '**Lift into a bid: %s**' % ('OK' if liftok else 'BLOCKED'), '']
        for tier, items in [('BLOCKER', B), ('CAUTION', C), ('INFO', I)]:
            for it in sorted(set(items)): L.append('- %s: %s' % (tier, it))
        L.append('')
    if a.requirements:
        stat = {}
        for path in glob.glob('method_statements/MS-*.md'):
            hh, _ = header(path)
            if hh.get('statement_id'): stat[hh['statement_id']] = hh
        cov = {}; inside = False
        for line in open('tender_requirements/%s.md' % a.requirements, encoding='utf-8'):
            line = line.rstrip('\n')
            if line.startswith('## item:'): inside = line.split(':', 1)[1].strip() == 'coverage'; continue
            m = re.match(r'^([a-z0-9_]+): (.*)$', line) if inside else None
            if m and m.group(1) != 'label' and m.group(1) != 'reading': cov[m.group(1)] = m.group(2)
        L += ['## Coverage of %s questions by method statements' % a.requirements, '', '| Question | Route | Statement status | Evidence class | Note |', '|---|---|---|---|---|']
        nm = 0
        for q, v in cov.items():
            route, _, note = v.partition('|'); route = route.strip(); sid = route.split()[-1] if route.startswith('PARTIAL') else ''
            if route.startswith('MISSING'): nm += 1
            st = stat.get(sid, {})
            L.append('| %s | %s | %s | %s | %s |' % (q, route, st.get('status', '') if sid else '', st.get('evidence_class', '')[:40] if sid else '', note.strip()))
        L += ['', '%d of %d questions have no statement. MISSING means no statement and no registered method, not that the firm lacks the capability.' % (nm, len(cov)), '']
    os.makedirs('method_views', exist_ok=True)
    open('method_views/statements.md', 'w', encoding='utf-8').write('\n'.join(L) + '\n')
    print('method_views/statements.md written')

if __name__ == '__main__':
    main()
