#!/usr/bin/env python3
"""Method view: read-only. Run from the toolkit root.  python3 tools/method_view.py [--family EVALUATION]

For each method statement in method_statements/ lists its status, our stated role, the applications it rests on
(from 03_methods.csv, or from method_new_rows_DRAFT.csv while those rows are still proposed) with project, contracting
arrangement and citation status, and the claims behind it with their type. A statement with no application, a
superseded statement, or an application whose method row is only PROPOSED is flagged. Nothing is ranked.
Output: method_views/statements.md (derived).
"""
import argparse, csv, glob, os, re

def rows(p):
    with open(p, newline='', encoding='utf-8') as f:
        return list(csv.DictReader(f))

def header(path):
    d = {}; inside = False
    for line in open(path, encoding='utf-8'):
        line = line.rstrip('\n')
        if line.strip() == '---': inside = not inside; continue
        if inside:
            m = re.match(r'^([a-z_]+): (.*)$', line)
            if m: d[m.group(1)] = m.group(2)
    return d

def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--family'); a = ap.parse_args()
    meth = {m['method_id']: dict(m, _src='03_methods.csv') for m in rows('03_methods.csv')}
    if os.path.exists('method_new_rows_DRAFT.csv'):
        for m in rows('method_new_rows_DRAFT.csv'):
            meth.setdefault(m['method_id'], dict(m, _src='proposed, not yet in 03_methods.csv'))
    proj = {p['project_id']: p for p in rows('01_projects.csv')}
    claims = {c['claim_id']: c for c in rows('04_claims.csv')}
    L = ['# Method statements (derived, read-only)', '', 'Generated by `tools/method_view.py`. Not a ranking. Wording is capped at the evidence class of the claims listed (ontology decision 11).', '']
    for path in sorted(glob.glob('method_statements/MS-*.md')):
        h = header(path)
        if a.family and h.get('family') != a.family: continue
        flags = []
        if h.get('status') != 'CURRENT': flags.append('status %s (not CURRENT)' % h.get('status'))
        if h.get('status') == 'SUPERSEDED': flags.append('SUPERSEDED: do not use as current')
        L += ['## %s %s' % (h['statement_id'], h['name']), '', '- Family: %s. Status: %s. Reviewed by: %s' % (h['family'], h['status'], h.get('reviewed_by', '')),
              '- Our role: %s' % h.get('our_role', ''), '- Disclosure check: %s' % h.get('disclosure_check', ''), '', '| Application | Project | Contracting | Citation | Method status |', '|---|---|---|---|---|']
        apps = [x for x in h.get('applications', '').split(';') if x]
        if not apps: flags.append('no application recorded')
        for mid in apps:
            m = meth.get(mid)
            if not m: L.append('| %s | not found | | | |' % mid); flags.append('%s not found' % mid); continue
            p = proj.get(m['project_id'], {})
            arr = p.get('contracting_role', '') or 'not recorded'
            if p.get('prime_contractor') and arr not in ('PRIME', 'DIRECT'): arr += ' to ' + p['prime_contractor']
            if m['method_status'] != 'APPLIED': flags.append('%s is %s' % (mid, m['method_status']))
            if m['_src'] != '03_methods.csv': flags.append('%s not yet registered' % mid)
            L.append('| %s (%s) | %s (%s) | %s | %s | %s |' % (mid, m['_src'].split(',')[0], p.get('canonical_name', m['project_id']), m['project_id'], arr, p.get('citation_status', ''), m['method_status']))
        L += ['', 'Claims behind it:', '']
        for cid in [x for x in h.get('claims', '').split(';') if x]:
            c = claims.get(cid)
            L.append('- %s (%s): %s' % (cid, c['claim_type'] if c else 'NOT FOUND', (c['precise_proposition'][:110] if c else '')))
            if not c: flags.append('%s not found' % cid)
        L += ['', 'Flags: ' + ('; '.join(sorted(set(flags))) if flags else 'none'), '']
    os.makedirs('method_views', exist_ok=True)
    open('method_views/statements.md', 'w', encoding='utf-8').write('\n'.join(L) + '\n')
    print('method_views/statements.md written')

if __name__ == '__main__':
    main()
